### ISSUE TITLE
Unable to enter user profile

### ISSUE THREAD

**Issue by Mekapix** [stolksdorf/homebrewery#401] opened 2017-05-17 22:45 UTC
Hello,

Currently, I seem to be unable to access my user profile. When I try and access my profile by clicking on my email in the top right corner, I'm sent back to the main page instead of my user page, meaning I can't access any of the brews that I've currently made or any I make in future. I've tried this on chrome and firefox and I've got the same issue on each browser.

**Comment by calculuschild** [comment] 2017-05-18 02:25
Have you tried going to [this page](http://www.naturalcrit.com/login) and clicking the logout button, then logging fully back in? I'm still able to get to my profile page so it might be something simple as that on your end.

**Comment by Mekapix** [comment] 2017-05-18 05:43
That doesn't seem to work. I still just get redirected to the introduction page instead of going to my profile.

**Comment by Mekapix** [comment] 2017-05-18 05:54
![image](https://cloud.githubusercontent.com/assets/28767333/26188393/d944244e-3b96-11e7-94c7-e13877e9b49b.png)

If it helps any

**Comment by Mekapix** [comment] 2017-05-18 18:51
Ok, I found the problem. Turns out that if you try to login with your email address instead of your username, it logs you in but doesn't allow you access to your profile

**Comment by calculuschild** [comment] 2018-11-19 14:05
Closing this as a duplicate of #807

**Closed by calculuschild** 2018-11-19 14:05 UTC
