### ISSUE TITLE
Class Feature issue

### ISSUE THREAD

**Issue by ZaricaDemoni** [stolksdorf/homebrewery#694] opened 2018-05-16 05:19 UTC
It is putting the already writted material in spaces it makes. an example is going from 4 pages, to 17. it posts the correct stuff, but keeps reposting all previous pages into spots in it. making multiple pages of the same content with a random class related line here and there.

**Comment by calculuschild** [comment] 2018-05-17 12:45
Duplicate of #413.

We have a fix, but it hasn't been pushed live quite yet.

**Closed by calculuschild** 2018-05-17 12:45 UTC
Labels: duplicate
