### ISSUE TITLE
Issue with Getting the PDF

### ISSUE THREAD

**Issue by Pecclest** [stolksdorf/homebrewery#508] opened 2017-10-04 19:44 UTC
Hey,
So I just finished a sweet new homebrew kit and I tried to get the pdf. However, when the new window opens it says that I have 0 pgs, refuses to let me save as a pdf, and causes everything to freeze. What can I do to fix this?

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment] 2017-10-04 19:47
Looks like you forgot to provide the share link in your bug report. Can you
paste that in here for us? That will help a lot in figuring out the issue.

**Comment by Pecclest** [comment] 2017-10-04 19:53
http://homebrewery.naturalcrit.com/share/S1m1yJyln-

**Comment by Pecclest** [comment] 2017-10-04 21:07
I'll try again. Thanks for letting me know about the double ranger thing. I
just tried it and nothing happened. I wonder if it might be an issue with
my computer?

**Comment by Sansd20** [comment] 2017-10-04 21:34
What browser are you using and is it up to date?

**Comment by Pecclest** [comment] 2017-10-04 21:58
Chrome and I am pretty sure it's up to date.
How can I check?

**Comment by calculuschild** [comment] 2017-10-04 22:36
Let's see... I'm able to get a PDF just fine. What browser are you using?
Have you been able to create PDFs before?

**Comment by Pecclest** [comment] 2017-10-04 23:44
I've been able to create pdfs before, in fact I tried to make a pdf for
another file and I could do that fine.

**Comment by Pecclest** [comment] 2017-10-05 16:24
Don't know wheather this is connected or not but for some reason when I try
to change the text/pictures on pgs-10 t0 20  the document doesn't react
PLUS there seems to be a missing page of text between what the document
says are 9 and 10.

**Comment by Pecclest** [comment] 2017-10-05 16:34
Wherever the problem is it's located in the paladin pages! Every time I cut
and paste the paladin pages back into the doc, the print preview that shows
what you are doing to the doc freaks out!

**Comment by Pecclest** [comment] 2017-10-05 16:54
Ok, I figured it out. Apparently there was a misplaced /div tag that was
screwing everything up. It works fine now! Thanks for the Help!

Peter

**Comment by calculuschild** [comment] 2018-04-21 23:55
Duplicate of #655

**Closed by calculuschild** 2018-04-21 23:55 UTC
