### ISSUE TITLE
Stat labels are doubled when exporting to PDF

### ISSUE THREAD

**Issue by ashleyhennefer** [stolksdorf/homebrewery#624] opened 2018-02-23 07:29 UTC
Stats are rendering weird; the labels somehow double for some of the stat blocks. It looks fine in the preview, but when exported to PDF, it looks like this:

![image](https://user-images.githubusercontent.com/7192335/36582878-11120ef4-1828-11e8-9acd-d04c58f9529b.png)

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/edit/SJN2H0cilM

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by HeruAsatru** [comment] 2018-02-23 08:28
Can't reproduce with the link you posted.

If it is still happening for you, you might try adding the following to your <style>

```
	thead {
		display: table-row-group;
	}
```

**Comment by granack** [comment] 2018-02-24 03:56
Also, make sure you are using Chrome and its built in "Save to PDF" printer. The site is optimized for that, to the detriment of other browsers.

**Comment by ashleyhennefer** [comment] 2018-02-24 03:59
That code fixed the issue, thank you!  😊

**Comment by calculuschild** [comment] 2018-04-10 13:47
Duplicate of #318

**Closed by calculuschild** 2018-04-10 13:47 UTC
Labels: duplicate
