### ISSUE TITLE
Screen cuts off halfway (screenshot included)

### ISSUE THREAD

**Issue by BaronMurph** [stolksdorf/homebrewery#233] opened 2016-11-27 19:58 UTC
After having to forcequit Chrome for reasons a little to complicated to go into, my screen looks like this: [http://i.imgur.com/bj0T3v4.png](url)
This is only for editing and my profile page; the share link displays a page that looks perfectly fine.
The issue isn't there in Microsoft Edge, but, you know, the program's optimalised for Chrome, so I want to be able to work with it in Chrome.
I've tried quitting Chrome, restarting Windows, changing zoom, even reinstalling Chrome, but nothing seems to work.
So, ah - help?

(And something else entirely; while reinstalling Chrome I fucked up and almost forgot my account name; thankfully, I remembered that the system fucks up and lists spaces in account names as %20, so I remembered that my name wasn't BaronMurph, but Baron Murph (or, as it listed it on my account page, Baron%20Murph). 
That's one issue - the %20 - and the other one is a suggestion, that there should probably be an (optional?) section to creating an account where you could list your e-mail for possible account name/password recovery, in case you forget like I almost did.)

EDIT: Running Chrome version 54.0.2840.99m, on Windows 10.

**Comment by TheGeffenM** [comment] 2016-11-27 21:17
I would also like to report this exact same issue. I am running Chrome version 54.0.2840.99m, running on a Windows 7 Ultimate x64 OS. Its extremely strange as I was just using it yesterday without any issues, and now all of the sudden its crushing the page down to about half the height of my Chrome window.

**Comment by numberQ** [comment] 2016-11-27 21:21
I'm getting the same issue, also using Chrome 54.0.2840.99m in Windows 7. I can sort of fix it by going into the HTML inspector and manually tweaking the heights in the style attributes for the text editor and preview panes.

**Comment by TheGeffenM** [comment] 2016-11-27 21:30
I used a CSS Editor Plugin to expand the size of the div.phb, but that seems to only fix the Preview pane, not the panel for entering text.

**Comment by VeritableTwenty** [comment] 2016-11-27 21:30
I too am experiencing this exact issue.  I am using Chrome Version 54.0.2840.99 m, running in Windows 10 Home x64.

**Comment by TheGeffenM** [comment] 2016-11-27 21:40
A temporary workaround that you all could use if you felt so inclined, which has been working for me.
Open Chrome App Store, download StyleBot.
Open the homebrew page, click the little CSS icon to the right of the web address bar, and hit Open Stylebot.
Hover your mouse over the space between the two panels and a green outline should appear around the "shrunk" panels.
Click it, and in the right hand panel, scroll down and select the Height field, type in 1080, then refresh the page.
Hopefully theres an official fix for this soon!

**Comment by akaddk** [comment] 2016-11-27 21:50
Just adding to the pile that I'm experiencing the same issue.

**Comment by BaronMurph** [comment] 2016-11-27 22:01
TheGeffenM's solution works pretty damn well for now, so I'll just advise anyone experiencing the same problem to try it - I set the size to 726 pixels (I think? Can't remember off the top of my head) to keep it from exceeding the size of the browser.

**Comment by madsimmons07** [comment] 2016-11-27 22:40
I think the issue is with the new Chrome update.  I too am seeing this on my laptop.  Anyone using TheGiffenM's fix should change the height to about 120 pixels less than your screen resolution height for best results, not just any arbitrary number.

**Comment by stolksdorf** [comment] 2016-11-28 00:01
Thanks for the reports guys. Everything is fixed in v2.5.2! 

I suggest disabling the Stylebot fix is it might not play right with other parts of the site (depending on how you coded it). Happy homebrewing!

**Closed by stolksdorf** 2016-11-28 00:01 UTC
