### ISSUE TITLE
Unable to Delete Brew

### ISSUE THREAD

**Issue by TamsynnImogen** [stolksdorf/homebrewery#455] opened 2017-07-30 12:16 UTC
Im unable to delete my brews one of them is broken but when i tried to use the delete bin icon nothing happens

brew in question is http://homebrewery.naturalcrit.com/edit/Hkz08bjiJW

![brew](https://user-images.githubusercontent.com/11425374/28753243-59ae04a8-7529-11e7-9cd0-5bf7d4b998c0.png)

**Comment by mrite** [comment] 2017-08-20 03:38
I have the same problem. Was this resolved? Can you delete it, or is it stuck on your page forever?

**Comment by calculuschild** [comment] 2018-04-10 17:25
Duplicate of #655

**Closed by calculuschild** 2018-04-10 17:25 UTC
