### ISSUE TITLE
Yet another class table rendering issue

### ISSUE THREAD

**Issue by Foxfire94** [stolksdorf/homebrewery#639] opened 2018-03-22 04:13 UTC
As the title says, this is yet another issue with the class table formatting looking fine until saved/loaded when it begins clipping with the text below. I tried adding padding below the table which works for 2-3 refreshes before it breaks again.

This issue isn't limited to this particular brew either, all four I've made have this issue. Also whilst I'm here, what does the "Recent Brews" button do? It seems to serve no purpose. Also a button on the top bar to start a new brew rather than having to go to the homepage to so it would be a nice ease-of-life improvement.

Update: I've temporarily fixed this with the dumbest of additions, a full stop using the ## head after the class table in the code. it causes enough of a buffer to not make it overlap and occasionally hides itself in the class table to boot. Not elegant but practical and better looking than clipping text.

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/BJPD71RFG

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

<div class='classTable wide'>
##### The Inquisitor
| Level | Proficiency Bonus | Features | Cantrips Known | Spells Known | 1st | 2nd | 3rd | 4th | 5th |
|:---:|:---:|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| 1st | +2 | ─ | 2 | 3 | 2 | — | — | — | — |
| 2nd | +2 | ─ | 3 | 2 | 3 | — | — | — | — |
| 3rd | +2 | ─ | 3 | 2 | 3 | — | — | — | — |
| 4th | +2 | Ability Score Improvement | 4 | 3 | 3 | — | — | — | — |
| 5th | +3 | ─ | 5 | 3 | 4 | 1 | — | — | — |
| 6th | +3 | Ability Score Improvement | 5 | 4 | 4 | 3 | — | — | — |
| 7th | +3 | ─ | 5 | 4 | 4 | 3 | 1 | — | — |
| 8th | +3 | Ability Score Improvement | 6 | 5 | 4 | 3 | 1 | — | — |
| 9th | +4 | ─ | 7 | 5 | 4 | 3 | 3 | — | — |
| 10th | +4 | ─ | 7 | 5 | 4 | 3 | 3 | 2 | — |
| 11th | +4 | ─ | 7 | 6 | 4 | 3 | 3 | 3 | — |
| 12th | +4 | Ability Score Improvement | 8 | 7 | 4 | 3 | 3 | 3 | 1 |
| 13th | +5 | ─ | 9 | 7 | 4 | 3 | 3 | 3 | 2 |
| 14th | +5 | Ability Score Improvement | 10 | 7 | 4 | 3 | 3 | 3 | 3 |
| 15th | +5 | ─ | 11 | 7 | 4 | 3 | 3 | 3 | 3 |
| 16th | +5 | Ability Score Improvement | 11 | 8 | 4 | 3 | 3 | 3 | 3 |
| 17th | +6 | ─ | 11 | 9 | 4 | 3 | 3 | 3 | 3 |
| 18th | +6 | ─ | 12 | 9 | 4 | 3 | 3 | 3 | 3 |
| 19th | +6 | Ability Score Improvement | 12 | 10 | 4 | 3 | 3 | 3 | 3 |
| 20th | +6 | ─ | 12 | 10 | 4 | 3 | 3 | 3 | 3 |
</div>

## Class Features
As an inquisitor, you gain the following class features
#### Hit Points
___
- **Hit Dice:** 1d8 per inquisitor level
- **Hit Points at 1st Level:** 8 + your Constitution modifier
- **Hit Points at Higher Levels:** 1d8 (or 5) + your Constitution modifier per inquisitor level after 1st

#### Proficiencies
___
- **Armor:** Light armor, medium armor
- **Weapons:** Simple weapons, hand crossbows, rapiers, longswords, shortswords, warhammers
- **Tools:** None.
___
- **Saving Throws:** Dexerity, Wisdom
- **Skills:** Choose two from Arcana, Athletics, History, Insight, Intimidation, Nature, Perception, and Survival

#### Equipment
You start with the following equipment, in addition to the equipment granted by your background:
- *(a)* a rapier, *(b)* a longsword, *(c)* warhammer or *(d)* any simple melee weapon
- *(a)* a hand crossbow with 20 bolts or *(b)* a light crossbow with 20 bolts
- *(a)* five javelins or *(b)* any simple melee weapon
- 10 lint fluffs

</pre></code></details>

**Comment by calculuschild** [comment] 2018-04-12 12:53
The "Recent Brews" button used to list the most recent brews viewed from that browser. It unexpectedly stopped working a while back and hasn't been fixed.

**Comment by calculuschild** [comment] 2018-04-12 12:54
Duplicate of #295

**Closed by calculuschild** 2018-04-12 12:53 UTC
