### ISSUE TITLE
Headers for 'classTable' Repopulate in PDF

### ISSUE THREAD

**Issue by erinnoonan8** [stolksdorf/homebrewery#631] opened 2018-03-07 22:45 UTC
Hello!

Love the site. Super Useful!

When I export to a .PDF the headers of the 'classTable' populate every other row in the table, and overrun all of the text. Couldn't get it to go away despite the format. 

Thanks!

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

<div class='classTable'>
##### The Manicurist
| Level | Proficiency Bonus | Features | Genetic Banishing|
|:---:|:---:|:---|:---:|
| 1st | +2 | Statistical Occultism | +1 |
| 2nd | +2 | Seismological Divination | +2 |
| 3rd | +2 | Civil Alchemy | +2 |
| 4th | +2 | Ability Score Improvement, Spiritual Biochemistry | +2 |
| 5th | +3 | Torque Interfacer | +2 |
| 6th | +3 | Ability Score Improvement, Astrological Chemistry | +2 |
| 7th | +3 | Divinatory Mineralogy | +3 |
| 8th | +3 | Ability Score Improvement, Malefic Chemist | +4 |
| 9th | +4 | Demonic Anthropology | +4 |

</div>

</pre></code></details>

**Comment by HeruAsatru** [comment] 2018-03-13 11:49
This is not a problem with the homebrewery, rather with chrome. Add the following to the top of your document: 

```
<style>
    thead {
	    display: table-row-group;
    }
</style>
```

**Comment by calculuschild** [comment] 2018-03-15 11:14
It has been suggested before that the Homebrewery just add this bit of code to its stylesheets to avoid this issue; it doesn't seem to mess anything else up. Hopefully we can see that changed at some point.

**Comment by HeruAsatru** [comment] 2018-03-15 12:03
sure, they could do that, maybe it will happen once the new homebrewery is being developed. Just leaving this here for future reference: https://github.com/stolksdorf/homebrewery/issues/627

**Comment by calculuschild** [comment] 2018-04-10 13:45
Duplicate of #318

**Closed by calculuschild** 2018-04-10 13:45 UTC
