### ISSUE TITLE
PDF not generated correctly

### ISSUE THREAD

**Issue by csr-garcia** [stolksdorf/homebrewery#534] opened 2017-10-28 16:04 UTC
### Additional Details

PDF doesn't generate correctly for linked document, attribute headers like STR, DEX, etc. are printed multiple times.
[CR21 Clockwork Reliquary.pdf](https://github.com/stolksdorf/homebrewery/files/1424394/CR21.Clockwork.Reliquary.pdf)

**Share Link** : http://homebrewery.naturalcrit.com/share/HkbcWeFkAb

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by JonBupp** [comment] 2017-10-30 19:19
I'm having the same issue.
[Allip.pdf](https://github.com/stolksdorf/homebrewery/files/1428468/Allip.pdf)

http://homebrewery.naturalcrit.com/share/SkQWYxB0b

**Comment by Moi-Brisingr** [comment] 2017-11-01 21:05
Alright here you go guys:
http://homebrewery.naturalcrit.com/share/H1uU4hPCW
http://homebrewery.naturalcrit.com/share/S1mQiHnwRZ

Please tell me when you copy the source code... so I know when to remove them from my list. Don't want to clog that up with other peoples brews.

**Comment by JonBupp** [comment] 2017-11-09 19:22
Sorry for my delay in responding, things have been very busy for me recently.

When I go to save it as a pdf, it's now putting the bottom line graphic and page number onto a second page.

**Comment by NoelMock** [comment] 2017-11-11 19:43
Mine is having the same issue, where when I print, the Ability Scores do not print correctly and it seems to be adding a blank page between each page of text. I am printing from Chrome.

[http://homebrewery.naturalcrit.com/share/ByfPCJ0c-](url)

**Comment by Moi-Brisingr** [comment] 2017-11-11 20:50
NoelMock just add an empty line between your closing style tag and the first headline in line 6 and the ability scores will be fine.
I don't have the problem with blank pages so I can't help you with that.

**Comment by NoelMock** [comment] 2017-11-11 23:10
Thank you, sir!!! Yeah, the page thing is weird, but I can just print around it, until I figure out how to fix it.  Thank you again!

**Comment by forlackofabetternerd** [comment] 2017-11-13 05:51
Having the same issue. 4 tables underneath a wide, on the second page only. The headings overlap all the way down the tables when I print it (paper and pdf).

http://homebrewery.naturalcrit.com/edit/ryGTbuobp-

[The Homebrewery - NaturalCrit.pdf](https://github.com/stolksdorf/homebrewery/files/1465710/The.Homebrewery.-.NaturalCrit.pdf)

**Comment by NoelMock** [comment] 2017-11-13 18:04
I'm getting a similar problem as _forlackofabetternerd_

[http://homebrewery.naturalcrit.com/edit/S1M6twC8ob](url)

**Comment by Moi-Brisingr** [comment] 2017-11-13 21:10
forlackofabetternerd your problem is fixed. Don't put the pagenumber and the footer divs in two consecutive lines.

NoelMock on the second page you can't put anything in front of the spelllist just put the headline into the div and move the other line below the spelllist div. It won't look exactly the same but at least your talbe will print correctly.

And for gods sake people don't post your edit links. Anyone can go in there and edit or delete your brews.

**Comment by NoelMock** [comment] 2017-11-13 23:47
Thank you, sir!  I moved it to under the Spell List and it works!

**Comment by forlackofabetternerd** [comment] 2017-11-14 20:22
Thanks for the assist, @Moi-Brisingr! 

I deleted the brew link too, I had no idea haha

**Comment by calculuschild** [comment] 2018-04-10 17:14
Duplicate of #657

**Closed by calculuschild** 2018-04-10 17:14 UTC
