### ISSUE TITLE
Can't view my brews :((

### ISSUE THREAD

**Issue by LeaBourgeat** [stolksdorf/homebrewery#574] opened 2017-12-10 18:34 UTC
Every timer I create something, I can't acces my 'recent brews'-page. I click it, and nothing happens - what to do?

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment] 2018-04-21 23:47
The "Recent Brews" button has been broken for a while, but hopefully we can have it fixed soon.

You have a couple of options:
1) Save the URL to your brew somewhere so you can get back to it later.
2) Create a Homebrewery account. Your brews will appear in a list on your profile page.

**Comment by calculuschild** [comment] 2018-04-21 23:48
Duplicate of #577

**Closed by calculuschild** 2018-04-21 23:48 UTC
Labels: duplicate
