### ISSUE TITLE
Cannot Download PDF!

### ISSUE THREAD

**Issue by Sn4k3z34** [stolksdorf/homebrewery#598] opened 2018-01-11 20:14 UTC
whenever i click on the GET PDF link, it opens up my printer menu when "Get PDF" clearly refers to a digital file i can use on my electronic devices...  i have tried three different web browsers, and four different 'home brew pages' all with the same issue

http://homebrewery.naturalcrit.com/print/Sk-D5r2Vbz?dialog=true

-i have no idea what to put below this line...
-also why do i need two accounts to ask this question?  sort of repetitive.   
**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment] 2018-01-11 20:39
If you go to print it you can "print" it as a pdf. Change your printer to one of the PDF printers and it will create a digital file instead of printing on paper.

**Comment by calculuschild** [comment] 2018-04-10 15:25
Duplicate of #656

**Closed by calculuschild** 2018-04-10 15:25 UTC
