### ISSUE TITLE
Naming a brew

### ISSUE THREAD

**Issue by KosChris** [stolksdorf/homebrewery#622] opened 2018-02-18 19:53 UTC
Hey! I'm wondering if there is a way to change the name of your homebrew after it is created. I'm going to the main page that shows you your brews, and I cannot find the option to change the name of the brew itself. I have a typo in the name of mine :/ 

Thank you! 

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by Moi-Brisingr** [comment] 2018-02-19 06:43
Open the brew for editing. In the gray bar at the top look to the right of Editor, PHB, Tables Print. there is a button with 3 horizontal lines. Click it and simply change the title.

**Comment by KosChris** [comment] 2018-02-19 11:58
Oh man you're a life saver. Thank you so much!

On Feb 19, 2018 12:43 AM, "Moi-Brisingr" <notifications@github.com> wrote:

Open the brew for editing. In the gray bar at the top look to the right of
Editor, PHB, Tables Print. there is a button with 3 horizontal lines. Click
it and simply change the title.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/stolksdorf/homebrewery/issues/622#issuecomment-366601227>,
or mute the thread

**Comment by calculuschild** [comment] 2018-04-09 16:38
Duplicate of #328

**Closed** 2018-04-10 12:13 UTC
Labels: duplicate
