### ISSUE TITLE
Class table render bug

### ISSUE THREAD

**Issue by qrsyua** [stolksdorf/homebrewery#740] opened 2018-08-24 02:25 UTC
Whenever I try to print the a PDF for any brew i have, it renders super weird. I've tried many things to fix this but it seems to be related to how the table renders when going to be printed

**Comment by calculuschild** [comment] 2018-08-29 11:50
Looks like a duplicate of #683.

Please take a look at [this comment](https://github.com/stolksdorf/homebrewery/issues/683#issuecomment-390644400).

**Closed by calculuschild** 2018-08-29 11:50 UTC
