### ISSUE TITLE
Rendering problems

### ISSUE THREAD

**Issue by qrsyua** [stolksdorf/homebrewery#638] opened 2018-03-18 22:28 UTC
There is a problem with rendering where the class table overlaps with the text below it, only correcting itself once another character is typed.

Here is an example:

### Additional Details

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

<div class='classTable wide'>
##### The Elementalist
| Level | Proficiency Bonus | Strike | Rushes | Features | Spells Known | 1st | 2nd | 3rd | 4th | 5th |
|:----:|:--:|:----:|:-:|:------------------------------------|:---:|:---:|:---:|:---:|:---:|:---:|
| 1st  | +2 | 1d4  | 2 | Unarmed Strike, Elemental Rush      | —  | — | — | — | — | — |
| 2nd  | +2 | 1d4  | 2 | Spellcasting, Weaponless Charge     | 2  | 2 | — | — | — | — |
| 3rd  | +2 | 1d4  | 2 | Elemental Origin, Selective Channel | 3  | 3 | 2 | — | — | — |
| 4th  | +2 | 1d4  | 3 | Ability Score Improvement           | 3  | 3 | 2 | — | — | — |
| 5th  | +3 | 1d6  | 3 | Elemental Weapon                    | 3  | 4 | 3 | — | — | — |
| 6th  | +3 | 1d6  | 3 |                                     | 4  | 4 | 3 | — | — | — |
| 7th  | +3 | 1d6  | 3 | Origin Feature                      | 4  | 4 | 3 | — | — | — |
| 8th  | +3 | 1d6  | 3 | Ability Score Improvement           | 5  | 4 | 3 | — | — | — |
| 9th  | +4 | 1d8  | 4 | —                                   | 5  | 4 | 3 | 2 | — | — |
| 10th | +4 | 1d8  | 4 |                                     | 5  | 4 | 3 | 2 | — | — |
| 11th | +4 | 1d8  | 4 | Origin Feature                      | 6  | 4 | 3 | 3 | — | — |
| 12th | +4 | 1d8  | 4 | Ability Score Improvement           | 6  | 4 | 3 | 3 | — | — |
| 13th | +5 | 1d10 | 4 |                                     | 7  | 4 | 3 | 3 | 1 | — |
| 14th | +5 | 1d10 | 5 |                                     | 7  | 4 | 3 | 3 | 1 | — |
| 15th | +5 | 1d10 | 5 |                                     | 8  | 4 | 3 | 3 | 2 | — |
| 16th | +5 | 1d10 | 5 | Ability Score Improvement           | 8  | 4 | 3 | 3 | 2 | — |
| 17th | +6 | 1d12 | 5 | Origin Feature                      | 9  | 4 | 3 | 3 | 3 | 1 |
| 18th | +6 | 1d12 | 5 |                                     | 9  | 4 | 3 | 3 | 3 | 1 |
| 19th | +6 | 1d12 | 5 | Ability Score Improvement           | 10 | 4 | 3 | 3 | 3 | 2 |
| 20th | +6 | 1d12 | 5 |                                     | 10 | 4 | 3 | 3 | 3 | 2 |
</div>

<img 
  src='https://i.imgur.com/LgW24RY.png' 
  style='position:absolute; top:0px; right:0px; width:817px' />

### Creating a Elementalist
A core part to what an elementalist is is what their origins are. Most of them end up stumbling into their power without direction. There isn't usually guilds or gatherings of elementalists, as most don't even know of their power as being categorized. Although the powers granted by the elemental origin don't come until 3rd level, you should plan ahead on which element they succeed with and how that ties into who they are. Why did Mother Earth reach out to you? Did you find her? Where were you before you end up discovering your powers? Most elementalists are every-day no bodies who have had their life thrown sideways by the disovery of their powers.

How did you discover your powers? Was it accidental or did you actively search it out. Many elementalists were those searching for power, abandoning whatever powers they had before to uptake the new life they have found in front of them.

#### Quick Build
You can make an Elementalist quickly by following these steps. First, make Strength your highest ability score, followed by Wisdom. Second, choose the urchin background.
```
```

## Class Features
As an elementalist, you gain the following class features
#### Hit Points
___
- **Hit Dice:** 1d8 per elementalist level
- **Hit Points at 1st Level:** 8 + your Constitution modifier
- **Hit Points at Higher Levels:** 1d8 (or 5) + your Constitution modifier per fishmongerer level after 1st

#### Proficiencies
___
- **Armor:** Medium armour, Light Armour
- **Weapons:** Simple weapons, fists
- **Tools:** Alchemist's tools

___
- **Saving Throws:** Strength, Wisdom
- **Skills:** Your choice of two from: Acrobatics, Athletics, Arcana, Intimidation, Perception, Stealth, Survival

#### Equipment
You start with the following equipment, in addition to the equipment granted by your background:
- *(a)* a martial weapon or *(b)* two simple weapons
- *(a)* leather armour or *(b)* dragon scale armour
- *(a)* explorer's pack or *(b)* dungeoneer's pack

</pre></code></details>

**Comment by calculuschild** [comment] 2018-04-12 12:51
Duplicate of #295

**Closed by calculuschild** 2018-04-12 12:51 UTC
Labels: bug, complicated, duplicate
