### ISSUE TITLE
Sample Image while in Editor not Viewed

### ISSUE THREAD

**Issue by salseethrough** [stolksdorf/homebrewery#623] opened 2018-02-23 01:00 UTC
So, while I'm in the editor of my brew, the actual image of the page, what it's supposed to look like, isn't there. I also tried seeing if it could be seen from the shared link, but likewise, it isn't there.

### Additional Details

My other brews' image are all viewable.

**Share Link** : http://homebrewery.naturalcrit.com/edit/rkf44c4Srz

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by granack** [comment] 2018-02-24 04:02
... and the link is dead. Did you delete it?
Also, you should be sharing the 'share' link not your 'edit' link. the edit link lets anyone edit your copy. with the share link your stuff is safe(r) from evildoers.

**Comment by calculuschild** [comment] 2018-04-12 12:42
Looks like a duplicate of #655

**Closed by calculuschild** 2018-04-12 12:42 UTC
