### ISSUE TITLE
All Brew pages are missing both on Share and Edit leaving only the blue background.

### ISSUE THREAD

**Issue by ElDuxarino** [stolksdorf/homebrewery#425] opened 2017-06-19 03:06 UTC
All of my Brew pages are empty. Not even the page outline is visible, just the blue background. Had friends check the share link and it is empty on their side as well. Other people's pages appear to me though.

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment] 2017-06-19 03:07
There is an error in your code. Likely some HTML tag that has not been
properly closed. This causes the renderer to crash.

**Comment by ElDuxarino** [comment] 2017-06-19 03:11
But on all the pages? 4 Different ones? They all use similar formatting (character sheets for new players) but  before I closed the sheets they were all working fine.

**Comment by ElDuxarino** [comment] 2017-06-19 03:13
You know what. I removed 1 section and it worked. I know where the problem is now at least. Thank you.

**Comment by calculuschild** [comment] 2017-06-19 03:38
Yeah, if you have one single error in your brew, the entire thing will fail
to render. This is why v3.0 will not allow custom HTML directly in the
code, since if you look through the other bug reports, about 80% of them
are the same error as yours: invalid HTML. Instead, all CSS styling will be
done in a separate tab.

Also keep in mind as you are troubleshooting your code that sometimes
having several tags one line after another, Markdown will close them in the
wrong order, even though it looks fine in your code. So like if you have a
div in the line right after a header or table it might generate invalid
code and crash. In that case just add a blank row between your tags.

**Comment by calculuschild** [comment] 2018-04-10 17:10
Duplicate of #655 
Also see #657

**Closed by calculuschild** 2018-04-10 17:10 UTC
