### ISSUE TITLE
Monster stat blocks rendering odd in PDF

### ISSUE THREAD

**Issue by Runeblood** [stolksdorf/homebrewery#208] opened 2016-09-20 13:07 UTC
**If you are suggestting a feature or improvement**, delete everything here and just write your idea.

If you are reporting a bug, please fill out the details. If you don't, I will most likely just close the issue asking for more detail.

---

**Browser Type/Version**: Chrome

**Issue Description**: When monster entries go into the right hand column, there is an error in the pdf. When printed or viewed in PDF but not on the site, there are STR DEX CON INT WIS CHA across the entries at the top of the column. 

**Brew code to reproduce**: <details> http://homebrewery.naturalcrit.com/edit/HyV14Y_ah <summary>

Click to expand code</summary>

```
PUT YOUR BREW CODE HERE
```

</details>

**Related Images** : IF APPLICABLE

**Comment by stolksdorf** [comment] 2016-09-20 14:51
Yup, looks like I bug. No idea what's causing it though.

**Comment by mshea** [comment] 2016-10-02 01:17
Same problem. Makes me very sad. It was working just a short bit ago! Any known way to work around it?

**Comment by vorpalhex** [comment] 2016-10-03 14:19
For what it's worth, it seems to be happening in Chrome 53 only. 

Chrome 54 (Beta) - Fine
IE 11/Safari 5.1 - Fine (or rather, at least don't have this issue)
Firefox 48 - Fine

**Comment by Runeblood** [comment] 2016-10-03 15:02
Thank you! I'll take a look at it in a different browser and see what's up

**Comment by SecretShop** [comment] 2016-10-17 15:38
Same issue as everyone above. Here is my page:
http://homebrewery.naturalcrit.com/share/S1Lwnie1g

**Comment by Plasma-Wisp** [comment] 2016-12-16 01:52
Also Applies to Safari on Mac

**Comment by calculuschild** [comment] 2017-01-24 23:30
I am no longer seeing this problem on PDFs made from the shared brews above.  This might be fixed.

**Comment by calculuschild** [comment] 2018-04-11 16:59
Duplicate of #318

**Closed by calculuschild** 2018-04-11 16:59 UTC
Labels: bug, complicated, duplicate
