### ISSUE TITLE
Real time version window  disappears after a period of time.

### ISSUE THREAD

**Issue by RattiganIV** [stolksdorf/homebrewery#247] opened 2016-12-07 03:39 UTC
this includes both my homebrews and the mainpage for homebrew.
the window that displays the "final product" just disappears, so i cant see what i'm doing, while trying to look up the issue, the main page stopped displaying correctly as well.

#update: the system works with edge, but still doesnt work with chrome

### Additional Details

**Share Link** :
http://imgur.com/ZXfE5pM
or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by PercussiveRepair** [comment] 2016-12-07 22:10
I get the same issue. Not sure if relevant but the errors in the Chrome debug console are: 
Uncaught Error: Minified React error #32; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=32&args[]=147 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.(…)
bundle.js:1 Uncaught TypeError: Cannot read property 'firstChild' of undefined(…)

**Comment by RattiganIV** [comment] 2016-12-09 22:05
this kind sucks massively, i have no idea what the issue is, breaks the whole thing because it optimized ONLY for chrome.

**Comment by PercussiveRepair** [comment] 2016-12-10 15:21
Closed? Still an issue for me

**Comment by stolksdorf** [comment] 2016-12-10 23:34
If other people are still having issues, I'm going to re-open this.

**Comment by Docrimbo** [comment] 2016-12-12 14:15
Same here. It's a bummer.

I can see it when I "get pdf," but not while updating in real time.

**Comment by stolksdorf** [comment] 2016-12-12 15:32
Not really sure what is causing this. I can't replicate it on my end. I have a feeling it's related to debounce saving getting out of sync. Pushing out an update, `v2.6.1` that adds additional protection for this. Let's see if it fixes it.

**Comment by PercussiveRepair** [comment] 2016-12-12 18:25
This is the brew that's currently not working for me: http://homebrewery.naturalcrit.com/edit/Hkxlxow2mx (and a previous one with the same content: http://homebrewery.naturalcrit.com/edit/Bkz9Vd-U7e) I tried creating a new one and pasting over the same text but it does the same thing. The preview works on the sample brew but as soon as I paste, the preview disappears.

**Comment by Docrimbo** [comment] 2016-12-13 00:15
When I try PercussiveRepair's method, the preview disappears when I save.

**Comment by stolksdorf** [comment] 2016-12-13 00:43
Thanks @PercussiveRepair, I can now replicate the issue and I know what's causing this. I'll fix it as soon as I have some free time. 

Note to future me: Edge case in error handling of open tag mismatch on fresh render.

**Comment by RattiganIV** [comment] 2016-12-13 16:55
My issue resolved itself spontaneously.

**Comment by calculuschild** [comment] 2016-12-24 05:51
I am having the same issue. One of my brews just refuses to render.

**Comment by Ryxian** [comment] 2017-01-19 14:39
I am currently having the same issue. I  can pull up a new doc and it is fine but as soon as I save it disappears.

**Comment by stolksdorf** [comment] 2017-01-19 17:48
Fixed in `v2.7.0` ᶦ ʰᵒᵖᵉ

**Comment by HiAverageJoe** [comment] 2017-02-01 00:36
Hello there, I've only been using the HomeBrewery for about a week and I am experiencing the same issue. There is no error message and I have checked every div tag with no success. My experience is similar to PercussiveRepair's.

![bug](https://cloud.githubusercontent.com/assets/25470024/22490685/9c3546da-e7ec-11e6-83e3-b8b6d120c441.png)
)

**Comment by Teetengee** [comment] 2017-06-08 13:52
I am also seeing the same problem with one of my brews. As soon as I save, the display disappears. Print to PDF still works, but the real-time editing is very powerful.

http://homebrewery.naturalcrit.com/share/Hy11ypUf-

for the share

**Comment by stolksdorf** [comment] 2017-06-08 14:09
@Teetengee Bad HTML and markdown mixing. Line 39. A div is being rendered within a header.

**Comment by Teetengee** [comment] 2017-06-08 17:03
Thanks, I removed it and got it to display again. That being said, that code displays fine before saving and when exporting to pdf, is that expected?

**Comment by calculuschild** [comment] 2018-04-18 00:30
This is the common issue #655 . As seen in the screenshot of the OP, he has an invalid `<div>` tag.

Closing and marking as duplicate of #655 .

**Closed by calculuschild** 2018-04-18 00:30 UTC
Labels: duplicate, ready to add
