### ISSUE TITLE
Error printing

### ISSUE THREAD

**Issue by Sansd20** [stolksdorf/homebrewery#510] opened 2017-10-06 22:05 UTC
When I go to print, I get some odd black marks on the "Encounter Building" table for the 1st two pages. I have tried different ways to get this to work. It even prints this way.

Looking at the print out, it looks like the table header is being printed over and over again, just a few pixels down.

### Additional Details

http://homebrewery.naturalcrit.com/share/rJY-3OrnZ

**Comment by Sansd20** [comment] 2017-10-07 18:14
More info.

It looks like the issue happens when there is a wide monster block and  a standard table after the block.

**Comment by calculuschild** [comment] 2018-04-10 17:04
Duplicate of #318

**Closed by calculuschild** 2018-04-10 17:04 UTC
