### ISSUE TITLE
Big: 'Recent Brews' -> 'Edited' stopped working

### ISSUE THREAD

**Issue by drewkunas** [stolksdorf/homebrewery#514] opened 2017-10-10 14:53 UTC
When you go to 'Recent Views' in the upper right, the link doesn't work.  The 'Viewed' option doesn't work either.  

This makes it impossible to access recent brews you didn't happen to save the link to.

Checked with both Chrome and Safari.  Cursor changes to a hand, indicating that it believes it's an on a link, but there's just absolutely no effect of clicking on it.

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment] 2018-04-21 23:53
Duplicate of #577

**Closed by calculuschild** 2018-04-21 23:53 UTC
