### ISSUE TITLE
Problem with PDF "Descriptive Text Box"

### ISSUE THREAD

**Issue by marcuswallace1991** [stolksdorf/homebrewery#779] opened 2018-10-19 22:25 UTC
Hello, 
I have problems with my Descriptive Text Box. 
When i'm write is all right, when I save in pdf the right side of the every table in the document is very bad to see. 
Can someone help me with this problem? 
Ty 

PS I have similar problem with a table: In the homebrewery it seems all ok, after i save in pdf I have a space that i don't want

**Comment by RKuerten** [comment] 2018-10-21 14:11
This is a duplicate of #683. Solution is there.

**Comment by calculuschild** [comment] 2018-11-09 20:36
Closing because this is a duplicate.

**Closed by calculuschild** 2018-11-09 20:37 UTC
