### ISSUE TITLE
Stat labels repeating themselves

### ISSUE THREAD

**Issue by HongKongBrewey** [stolksdorf/homebrewery#641] opened 2018-03-24 02:05 UTC
The brew looks fine in the preview, but when I try to export in pdf form the stat labels cascade and multiply.

### Additional Details

**Share Link** : http://oi63.tinypic.com/2n6c1us.jpg

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

<img 
  src='http://i68.tinypic.com/11iepsz.jpg' 
  style='position:absolute;top:400px;left:-0px;width:816px' />
<img 
  src='https://i.imgur.com/cPPYV7h.png' 
  style='position:absolute;top:-180px;left:0px;width:916px' />
# The Arisen Goddess of the Astral Plane
### Marda Wetherspond (Nana Withers)
*"It's true, I am withering. Just like any beautiful flower does."*
<div style='margin-top:0px'></div>

Born in a tiny shire built into the hilly plains of the Kuuderian Empire Marda lived a typical Halfling life. She had her share of adventures, travelling the world as one fourth of an adventuring party set on claiming fame and glory, but that life swiftly overtook her when she met her husband, and the two of them settled down in Ani.

Her husband, Osver Wetherspond, made a decent living as an atilliator, making crossbows exclusively for the royal army. Marda became the local midwife and while payment for her services were rare due to her indiscriminate kindness there was always a steady flow of free food and gifts from grateful families who couldn't afford an alternative. As loathe as she was to part with such mementos there were times when pawning them off was neccessary to survive.

Marda  remembers every child she has ever brought into the world and considers them and their families to be her extended kin, as a result her home has become somewhat of a haven for those under that umbrella with people of all ages coming and going at all hours of the day, each and every one of them pressing a grateful kiss to the cheek of the one they lovingly nicknamed "Nana Withers."

Over time her desire to watch over her children and keep them safe manifested in powers fit for the new goddess of the astral plane. Quite often family members would find Nana Withers asleep, not knowing that she was wide awake in the astral realm checking in on somebody. The ability to see through the astral realm to far-away places allowed her to keep an eye on distant children and her ability to allow others to pass from one realm to another let her hide her children away from those that would do them harm.

More recently her dwelling has become a flop house for the Resistance Fighters of Ani, a small rebel force focused on opposing the reign of the Queen whom they believe to be an ego-driven tyrant despite the prosperity of the city and the love the populace has for their ruler.
<div style='margin-top:140px'></div>
<div style='margin-top:300px'></div>

### Playing Nana Withers
Contrary to her appearance and demeanor Nana Withers is a sprightly thing, her godhood giving her a newfound prowess. She doesn't desire to flaunt this though, being the wise woman suits her fine and she'll only exert herself in emergencies. When she does however she uses her talents to their fullest, which is a testament to her tenacity.

When she's not putting belligerents in their place she does her best to act as a mentor for those who cross her path, this isn't always obvious to those subjected to her child-like curiosity and impish sense of humor.

To those she doesn't know she is a kind lady who's interested in the tales of life, this is only partly a ruse designed to gauge the intent of visitors. To those whom she trusts she is the glue that holds everything together and will do everything in her power to extend to those in need a safe haven from the chaos of the world.
___
> ## Nana Withers
>*Small humanoid (halfling), Lawful Good*
> ___
> - **Armor Class** 12
> - **Hit Points** 55(22d6)
> - **Speed** 25ft.
>___
>
>|STR |DEX|CON|INT|WIS|CHA|
>|:---:|:---:|:---:|:---:|:---:|:---:|
>|12 (+1)|14 (+2)|9 (-1)|16 (+3)|16 (+3)|15 (+2)|
>
>___
> - **Condition Immunities** None
> - **Senses** passive Perception 13
> - **Languages** Halfling, Common, Thieves Cant
> - **Challenge** 1/2 (100 XP)
> - **Divinity Score** 15 (+2)
> ___
> ### Actions
> ***Multi-Attack*** Nana Withers can attack twice, once with each weapon, every other turn.

> ***Spear Thrust.*** *Melee Weapon Attack:* +5 to hit, reach 5ft., one target. *Hit* 5 (1d6/1d8+1) 
>
> ***Hand Crossbow Bolt*** *Ranged Weapon Attack:* +6, range 30/120, one target. *Hit* 4 (1d6+2) 

> ### Lair Actions
When inside her home Nana Withers can take the following actions on Initiative Count 20:

> ***Astral Banishment*** Nana Withers can pull up to five targets of her choosing into the Astral Realm and expell them in any location up to 500ft of her current position.

> ***Astral Evacuation*** Nana Withers can plunge her household and everyone in it, into the Astral Realm, leaving behind an empty building, it then replaces the inside of her home in Shrapnel Cliffs. 

</pre></code></details>

**Comment by calculuschild** [comment] 2018-04-10 13:41
Duplicate of #318

**Closed by calculuschild** 2018-04-10 13:41 UTC
