### ISSUE TITLE
"Table" section glitch

### ISSUE THREAD

**Issue by CCasath** [stolksdorf/homebrewery#763] opened 2018-09-29 09:14 UTC
When using a table from the pre coded "table" section. The outline markings glitch and display incorrectly when the document is being printed.

**Comment by Mamorudramon** [comment] 2018-10-15 19:53
I'm also seeing this error. When I hit <b>Get PDF</b>, I get the following...

![tableerrors](https://user-images.githubusercontent.com/44177764/46974540-24186980-d079-11e8-8ad7-03f1ef19b4e6.PNG)

Example Brew:

<style>
  .phb{
    width : 210mm;
    height : 296.8mm;
  }
</style>

<div class='classTable wide'>
##### The Fletcher
| Level | Proficiency Bonus | Features | Cantrips Known | Spells Known | 1st | 2nd | 3rd | 4th | 5th | 6th | 7th | 8th | 9th |
|:---:|:---:|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| 1st | +2 | Divinatory Mineralogy | 3 | 1 | 2 | — | — | — | — | — | — | — | — |
| 2nd | +2 | Gunpowder Torturer | 4 | 2 | 4 | — | — | — | — | — | — | — | — |
| 3rd | +2 | ─ | 4 | 2 | 4 | — | — | — | — | — | — | — | — |
| 4th | +2 | Ability Score Improvement, Seismological Divination | 5 | 2 | 4 | 1 | — | — | — | — | — | — | — |
| 5th | +3 | Gunpowder Torturer | 5 | 3 | 4 | 2 | — | — | — | — | — | — | — |
| 6th | +3 | Ability Score Improvement, Exo Interfacer | 5 | 4 | 4 | 3 | 1 | — | — | — | — | — | — |
| 7th | +3 | Orbital Gravedigger | 5 | 4 | 4 | 3 | 3 | — | — | — | — | — | — |
| 8th | +3 | Ability Score Improvement, Astrological Botany | 6 | 4 | 4 | 3 | 3 | 2 | — | — | — | — | — |
| 9th | +4 | Astrological Chemistry | 6 | 5 | 4 | 3 | 3 | 3 | — | — | — | — | — |
| 10th | +4 | Orbital Gravedigger | 6 | 5 | 4 | 3 | 3 | 3 | 1 | — | — | — | — |
</div>

<div class='classTable'>
##### The Archivist
| Level | Proficiency Bonus | Features | Gunpowder Torturer|
|:---:|:---:|:---|:---:|
| 1st | +2 | Malefic Chemist | +1 |
| 2nd | +2 | ─ | +2 |
| 3rd | +2 | ─ | +2 |
| 4th | +2 | Ability Score Improvement, Orbital Gravedigger | +2 |
| 5th | +3 | Astrological Chemistry | +3 |
| 6th | +3 | Ability Score Improvement, Infernal Banker | +3 |
| 7th | +3 | Immunological Incantations | +4 |
| 8th | +3 | Ability Score Improvement, Police Necromancer | +5 |
| 9th | +4 | Genetic Banishing | +5 |
| 10th | +4 | Spell Analyst | +6 |
</div>

```
```

<div class='descriptive'>
##### Time to Drop Knowledge
Use notes to point out some interesting information. 

**Tables and lists** both work within a note.

**Tables and lists** both work within a note.

**Tables and lists** both work within a note.

**Tables and lists** both work within a note.

**Tables and lists** both work within a note.
</div>

**Comment by Mamorudramon** [comment] 2018-10-15 20:08
This has actually already been solved and the solution in Issue 683 worked perfectly.

**Comment by AlexeySachkov** [comment] 2018-10-16 07:47
Hi, @CCasath 

@Mamorudramon is right, there is a workaround: see [this comment](https://github.com/stolksdorf/homebrewery/issues/683#issuecomment-390644400) in #683

**Comment by calculuschild** [comment] 2018-11-13 13:32
Closing because this is a duplicate of #683 .

**Closed by calculuschild** 2018-11-13 13:32 UTC
Labels: duplicate
