### ISSUE TITLE
Broken Table Item Names

### ISSUE THREAD

**Issue by AlbertMokrejs** [stolksdorf/homebrewery#214] opened 2016-10-10 00:53 UTC
**Browser Type/Version**: Chrome Version 53.0.2785.116 m

**Issue Description**: 

A table of mine displays bolded versions of the table's item names over the table itself, making it gross and hard to read. Because this brew is lengthy, I'm only including an image of that page. The full brew is [here](http://homebrewery.naturalcrit.com/share/rJm70I39p). 

Other tables in this document work fine though, for some reason.

**Brew code to reproduce**:

```
 \page 

<div class='pageNumber auto'></div>

<div style='margin-top:50px'></div>

<div class='classTable wide'>
##### Core / Special Attribute Advancement Cost [in 1000s of Valor]
| Rank| 1 | 2 | 3 | 4| 5 |6 | 7 | 8 | 9 | 10 | 11 | 12 |
|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|1|0|
|2|2|0
|3|5|3|0|
|4|9|7|4|0
|5|15|13|10|6|0|
|6|23|21|18|14|8|0
|7|33|31|28|24|18|10|0|
|8|45|43|40|36|30|22|12|0
|9|60|58|55|51|45|37|27|15|0|
|10|78|76|73|69|63|55|45|33|18|0
|11|99|97|94|90|84|76|66|54|39|21|0|
|12|123|121|118|114|108|100|90|78|63|45|24|0|
</div>

<div style='margin-top:30px'></div>


<div class='classTable wide'>
##### Special Attribute Advancement Cost [in 1000s of Valor]
| Rank| 12|13|14|15|16|17|18|19|20|21|22|23|24|
|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|12|0
|13|28|0
|14|60|32|0
|15|96|68|36|0
|16|136|108|76|40|0
|17|181|153|121|85|45|0
|18|231|203|171|135|95|50|0
|19|286|258|226|190|150|105|55|0
|20|347|319|287|251|211|166|116|61|0
|21|414|386|354|318|278|233|183|128|67|0
|22|487|459|427|391|351|306|256|201|140|73|0
|23|566|538|506|470|420|385|335|280|219|152|79|0
|24|651|623|591|555|505|470|420|365|304|237|164|85|0

</div>

<div style='margin-top:10px'></div>



##### Sample Attribute Arrays
| Array | Description | Cost |
|:----:|:-------------:|:----:|
| 5,5,5,5,4,4,4,4 | Discounted | 56,000 |
| 5,5,5,5,5,5,5,5 | Balanced|80,000 |
| 6,6,5,5,5,5,4,4  | Mildly Specialized | 84,000|
| 7,6,6,6,5,4,4,4 | Specialized | 104,000|
| 8,7,6,5,5,5,4,4 | Advanced | 124,000 |
| 10,5,5,4,4,4,3,3 | Min-Maxed | 105,000 |

<div style='margin-top:10px'></div>

Enhancing attributes provides broad bonuses via the skills and derived characteristics that benefit from them. Failing to invest sufficiently into the right attributes can lead to a crusader having a harder time keeping up to their peers through a sheer inequality of ability. However, over-investing in attributes can leave characters short on valor to spend on qualities which provide unique benefits and utility. 

Players should also carefully consider which attributes are the most important for their unique role in the group, so as the best capitalize on their strengths and counter their weaknesses. 

<div style='margin-top:10px'></div>


\page 

```

</details>

**Related Images** : ![homebrew](https://cloud.githubusercontent.com/assets/8742460/19225100/ff7275ae-8e61-11e6-870a-1f96ec22591b.png)

**Comment by vorpalhex** [comment] 2016-10-10 01:20
This seems to be the same issue as #208. Using Chrome 54 (beta) or Firefox should dodge the issue for now so you can get a PDF export, but this is a complicated and browser specific error due to a bug in Chrome 53.

**Comment by calculuschild** [comment] 2018-04-11 16:58
Duplicate of #318

**Closed by calculuschild** 2018-04-11 16:58 UTC
Labels: duplicate
