### ISSUE TITLE
Brew not rendering

### ISSUE THREAD

**Issue by Athelforth** [stolksdorf/homebrewery#557] opened 2017-11-21 20:15 UTC
Hi all,

My brew was working perfectly until about 3 hours ago. For some reason it has decided to no longer render my brew. I still see the Edit box with all my code in, and the rest of the site works normally, as do my other brews.

Quite stumped if I'm honest. Source for the brew is here http://homebrewery.naturalcrit.com/source/SkZkAvZGlz

Hoping somebody can help,
Thanks

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by Moi-Brisingr** [comment] 2017-11-21 20:42
On the page that starts with the "Hunter's Arsenal" headline your footnote is not a div but a dive. Also if you want this to convert to pdf correctly separate the pagenumber and footnote divs with blank lines.

**Comment by Athelforth** [comment] 2017-11-21 20:53
Ah, a simple mistype! How could I! Thank you so much for that, brew appears to be rendering normally now, although I have had to past it into a fresh brew to get it to save. The advice regarding blank lines is much appreciated also. Thanks

**Comment by calculuschild** [comment] 2018-04-10 15:51
Duplicate of #655

**Closed by calculuschild** 2018-04-10 15:51 UTC
