### ISSUE TITLE
Nothing showing in the render window

### ISSUE THREAD

**Issue by kelldenar** [stolksdorf/homebrewery#394] opened 2017-05-08 06:52 UTC
Aloha! First off, absolutely great work on the Homebrewery! Love it! Love it! Love it! Hats off to you guys! Ok, so now my issue. I've been working on my code and everything was going fine until I saved and now nothing shows up in the render window yet when I go to Get PDF it shows up fine. Is there something I can do to fix this? Any help would be greatly appreciated!

### Additional Details

**Share Link** :http://homebrewery.naturalcrit.com/edit/rylM-68Une

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

<img 
  src='http://pre08.deviantart.net/4599/th/pre/f/2017/091/1/7/ashenguarde_phb_logo_by_bigmaka-db49x9a.jpg' 
  style='position:absolute;bottom:20px;top: 20px; left:20px' />
 
  

\page
<div class='toc'>

# CONTENTS
### Preface
 <div style='margin-top:1px'></div>
### Introduction
  Worlds of Adventure....................................................................4
  Using this Book............................................................................4
  How to Play..................................................................................5
  Adventures....................................................................................5
#### Chapter 1: Step-by-step characters......5
Beyond 1st Level..........................................................................6
#### Chapter 2: The Alliances..........................................7
- ##### The Armies of Darkness
   - Abyssalkin.............................................................................8
   - Anir........................................................................................9
   - Cyclopeans...........................................................................10
   - Ettins.....................................................................................11
   - Gnollkin................................................................................12
   - Trolls.....................................................................................13
   Vampire................................................................................14
   
- ##### Bearers of the Light
   - Aszkor...................................................................................15
   - Dwarves................................................................................16
   - Elves......................................................................................17
   - Fey'dren.................................................................................18
   - Gauls......................................................................................19
   - Gnomes..................................................................................20
   - Halflings.................................................................................21
   
- ##### The Federation
   - Centaurs..................................................................................22
   - Half-Orcs................................................................................23
   - Humans...................................................................................24
   - Naga........................................................................................25
   - Satyrs......................................................................................26
   - Northern Tribes.......................................................................27
   - War-Mech...............................................................................28
   
#### Chapter 3: Classes..............................29
- ###### Artificers.......................................................................................30
  - Federation Alchemist
  - Traps Sabotoeur
  - Vials Master
  - Gadget Engineer
- ###### Barbarians......................................................................................42
  - Path of the Spellbreaker
  - Path of the Blood Reaver
  - Path of the Sadist
  - Path of the Mastadon
  - Path of the Chain
  <div style='margin-top:100px'></div> 
- ###### Bards........................................................................................50
  - Seichi Warbringer
  - Voodooo Bluesman
  - Summoner of Caed
  - Death's Voice
  - Blades of GuZheng
- ###### Clerics.......................................................................................61
  - Ocean
  - Mountain
  - Void
  - Blast
  - Wrestling
  - Speed
  - Fury
- ###### Druids.......................................................................................80
  - Harvester of Sorrow
  - Wildwood Elder
  - Feral Savage
  - Stone Wardens
- ###### Fighters......................................................................................90
  - Monstrous Cavalier
  - Weapons Saint
  - Reaping Mauler
  - Bar Room Brawler
  - Borderlands Luchador
  - Power Wrestler
  - Shadow-ken Boxer
  - Disciple of Guan Yu
  - Master Pikesman
  - Defender of The Vale
  - Hand of Justice
- ###### Monks.......................................................................................110
  - Master of the Five Deadly Venoms
  - The Bei Shen Warrior
  - The Void Monk
  - Chi Na Disciple
  - Shotokan Sohei
  - Eight Trigram Staff Fighter
  - Twelve Kicks Master
  - Iron Fists Warrior
  - Acolytes of the Red Palm
  
- ###### Paladins.....................................................................................129
  - Oath of the Sharac
  - Oath of the Desert King
  - Oath of the Five Pagodas
  - Oath of the Sapphire Empire
  - Oath of the Crag
  - Oath of the North
  - Oath of the Spire
  - Oath of the Federation
  </div>
\page
<div class='toc'>

- ###### Rangers........................................................................................130
  - Bounty Hunter
  - City Stalker
  - Spell Sniper
- ###### Rogues.........................................................................................145
  - Cyprinian Seductress
  - The Masked Vigilante
  - Shade Walker
  - Plains Corsair
  - The Gambler
  - City Thug
  - Clan Ninja
  - The Divine Blade
- ###### Sorcerers......................................................................................170
  - Elemental Scion
  - Fiend Lord
  - Zodiac Caster
  - Infused
  - Psionicist
  - Sigil Master
- ###### Warlocks.......................................................................................180
  - The Raven Mother
  - The Circle of Twelve
  - The Teha Tua
  - The Light of the Seven
  - The Fenir
  - The Primordial King
  - The Old One
- ###### Wizards..........................................................................................195
  - Follower of The Hand 
  - The Tri-Mage
  - Master of Wands
  - Demon Bound
  - Fury Magus
  
#### Chapter 4: Personalities and backgrounds
- Apothecary<div style='margin-top:1px'></div>
Barkeep<div style='margin-top:1px'></div> 
Battle Scarred<div style='margin-top:1px'></div>
Exile<div style='margin-top:1px'></div>
Experiment<div style='margin-top:1px'></div>
Failed Jester<div style='margin-top:1px'></div>
Former Slave<div style='margin-top:1px'></div>
Librarian

#### Chapter 5: Equipment
- Starting Equipment<div style='margin-top:1px'></div>
Wealth<div style='margin-top:1px'></div>
Armor and Shields<div style='margin-top:1px'></div>
Weapons<div style='margin-top:1px'></div>
Adventuring Gear<div style='margin-top:1px'></div>
Tools<div style='margin-top:1px'></div>
Mounts and Vehicles<div style='margin-top:1px'></div>
Trade Goods<div style='margin-top:1px'></div>
Expenses<div style='margin-top:1px'></div>
Trinkets<div style='margin-top:10px'></div>

###### Starting Equipment<div style='margin-top:1px'></div>
Wealth<div style='margin-top:1px'></div>
Armor and Shields<div style='margin-top:1px'></div>
Weapons<div style='margin-top:1px'></div>
Adventuring Gear<div style='margin-top:1px'></div>
Tools<div style='margin-top:1px'></div>
Mounts and Vehicles<div style='margin-top:1px'></div>
Trade Goods<div style='margin-top:1px'></div>
Expenses<div style='margin-top:1px'></div>
Trinkets<div style='margin-top:10px'></div>
#### Chapter 8: Combat
<div style='margin-top:1px'></div>
#### Chapter 10: Spells
</div>

\page

# Introduction
on the world of Eriston, between the great blue expanse that is the Riddersack and the uncharted territories of the Inner Seas lies the contient of Aldverath where the remnants of the great alliances still stand and the colossal barrier of the Sharac looms silently along its coastlines. Ashenguarde ,the last bastion of hope against the ancient threat of the Vampire Nations, is but a shade of its former glory. The tales and battles that once took place has faded into myth, its heroes that fought against insurrmountable odds have become legend while the evils they fought have become nothing more than whispers lost to history. Until now....   

Directly to the south lies the wild, untamed lands of Ord, an undiscovered continent with ancient mysteries and cultures waiting to be found. Travelers and explorers from faraway kingdoms have begun to lay claim to the uncharted lands bringing them into direct conflict to the natives of that continent and each with each other. The conflicts have become to be known as the Bordertown Wars and new and devastating technologies and spells have been borne from the struggles.  

To the east, past the turbulent waters of the Savage Isles lies the continent of Laon where the Sapphire Empress desperately seeks to balance ruling her kingdom and preventing the demons from the Abyss from burning it into cinders.

### Remnants of old...
Sitting high above the bone white sands of Oderun Brae, perched upon the walls known as the Sharac,lies the last bastion of hope for the world against the darkenss, the City of Ashenguarde. Having once been apart of a great alliance of Elves, Dwarves, Gauls and Men, it has all but faded into obscurity and Ashenguarde alone remains. It's been nearly seven-hundred years since the last attempt occured by the Vampire Nations to take over the realms through sheer force of numbers.  Now, whispers and rumors from seasoned ocean travelers and explorers have reached the ruling council of Ashenguarde of strange black ships that billow clouds of smoke have been seen on the horizon and bears a standard no one recognizes anymore... 

### A broken pact...
Within the frozen tundras of the Northern Wastelands, deep within its arctic mountains, lies the final resting place of the two leaders that helped literally shaped this world. Aedin Cen, the General of Heaven and Taar Sarot, the Dragon Commander of the Nine Hells. After thousands of years of never-ending wars and battles with neither side gaining the advantage over the other it was said that the two great leaders brokered an accord. In that instant the scars of war disappeared and life began anew. New sentient races were given purpose, old and ancient races faded from memory and peace reigned for nearly a thousand generations. But now through unknown means the accord has been broken, the remains of the generals gone from their tombs and the rumblings of terrifying armies can be heard in the distance...
<div style='margin-top:900px'></div>
### Drums of war...
The splendors of the Eastern Realms are well known throughout all the lands. From the ports of The Tsing Tao Trading compay, with it's exotic trade of spices and slaves, to the Five Pagodas of Tsugane where each tower seemingly stretches on into the heavens. Here the war between The Red Palm disciples and the White Han has nearly escalated to all out civil war and only the current ruling family of the Saphire Empire can quell the fires before it burns the kingdom to the ground.  But now an old enemy has returned and with him a dark truth, one that can tear the ruling family apart...

### Out of time...
During the Age of Myth the Titans of Eriston fought amongst themselves for supremacy. Their titanic battles changed the very landscape into the world as it is today. During this tumultous time there was one god 

<div class='pageNumber auto'></div>

\page

In the world of Ashenguarde, each player creates an adventurer (also called a character) and teams up with other adventurers (played by friends). Working together, the group or party might explore a dark dungeon, a ruined city, a haunted castle, a lost temple deep in a jungle, or a lava filled cavern beneath a mysterious mountain. The adventurers can solve puzzles, talk with other characters, battle fantastic monsters, and discover fabulous magic items and other treasure. <div style='margin-top:1px'></div>

One player, however, takes on the role of the Game Master (GM), the game’s lead storyteller and referee. The GM creates adventures for the characters, which navigate its hazards and decide which paths to explore. The GM might describe what the details of Union Jack City are and provide the adventurers with various options of what they would like to do. Will they seek out their fortunes and test their luck at the gambling establishments in the city? Maybe they take up a bit of bounty hunting and grab a wanted poster and bring in the nearby Goblin Gangs to heel for a bit of reward money. <div style='margin-top:1px'></div>

Then the GM determines the results of the adventure’s actions and narrates what they experience. Because the GM can improvise to react to anything the player’s attempt, Ashenguarde is infinitely flexible, and each adventure can be exciting and unexpected.<div style='margin-top:1px'></div> 

The game has no real end; when one story or quest wraps up, another one can begin, creating an ongoing story called a campaign. Many people who play the game keep their campaigns going for months or years, meeting with their friends every week or so to pick up the story where they left off. The adventurers grow in might as the campaign continues. Each monster defeated, each adventure completed and each treasure recovered not only adds to the continuing story, but also earns the adventurers new capabilities. This increase in power is reflected in the adventurer’s skills and abilities. <div style='margin-top:1px'></div>

There’s no winning and losing in Ashenguarde – at least not the way those terms are usually understood. Together, the GM and the players create an exciting story of bold adventurers who confront deadly perils.<div style='margin-top:1px'></div>

Sometimes and adventurer might come to a grisly end, torn apart by ferocious monsters or done in by a nefarious villain. Even so, the other adventurers can search for powerful magic to revive their fallen comrade, or the player might choose to create a new character to carry on. The group might fail to complete an adventure successfully, but if everyone had a good time and created a memorable story, they all win.<div style='margin-top:10px'></div>
<img 
  src='http://livedoor.blogimg.jp/the_dd_on/imgs/a/5/a598e555-s.png' 
  style='width:348px' />
<div style='margin-top:100px'></div>

### THE NEVER ENDING WARS…
The Lands of Ashenguarde are vast and are never short on adventures to those that go out and seek it. Explore the realms of the treacherous Rock Trolls of the Ishkar Mountains where the Troll council convenes to make the laws of their twisted society. Or seek out the legendary Dwarven crafters in the Felheim Underground where it is said that they have unearthed the secrets to defeating the enemies of the Light. Become a War-Mech, a living, breathing and sentient automaton fueled by Arcane energies, originally created to be the secret weapon against the Armies of Tao Sar, you now seek a new purpose in this world. With endless possibilities at your disposal, gather up some friends and set out for an adventure thru Ashenguarde and let your names become legends!<div style='margin-top:1px'></div>

>##### Using this book
> The Core Rule Book is divided into the following sections:
>
>* **Part 1** is about creating a character, providing the rules and guidance you need to make the character you’ll play in the game. It includes information on the various races, classes, backgrounds, equipment and other customization options that you can choose from. Many of the rules in part 1 rely on material in parts 2 and 3. If you come across a game concept in part 1 that you don’t understand, consult the book’s index. <div style='margin-top:10px'></div>

>* **Part 2** details the rules of how to play the game, beyond the basics described in this introduction. That part covers the kinds of die rolls you make to determine success or failure at the tasks your character attempts, and describes the three broad categories of activity in the game: exploration, interaction and combat. <div style='margin-top:10px'></div>
>* **Part 3** is all about the arts. In Ashenguarde arts are divided by two categories: Combat Arts and Meta Arts. Combat Arts are comprised of the more physical aspects of combat such as wielding a hammer or using your bare knuckles to fight. Meta Arts have to deal with the more mystical or divine aspects of the world such as healing prayers or raising the dead. This section also introduces the Archetype concept. Here players will discover that when you combine certain skills or arts together they can create a special archetype or class that will provide them certain bonuses or abilities. 
<div class='pageNumber auto'></div>

\page

### HOW TO PLAY
Ashenguarde follows the standard flow of today’s tabletop RPG’s and uses the same basic pattern.
1. **The GM describes the environment.** The GM tells the players where their adventurers are and what’s around them, presenting the basic scope of options that present themselves (how many doors lead out of a room, what’s on a table, who’s in the tavern and so on. ) <div style='margin-top:10px'></div>
2. **The players describe what they want to do.** Sometimes one player speaks for the whole party, saying, “We’ll take the east door,” for example. Other times, different adventurers do different things: one adventurer might search a treasure chest while a second examines an esoteric symbol engraved on a wall and a third keeps watch for monsters. The players don’t need to take turns, but the GM listens to every player and decides how to resolve those actions. <div style='margin-top:1px'></div> 
Sometimes resolving a task is easy. If an adventurer wants to walk across a room and open a door, the GM might just say that the door opens and describes what lies beyond. But the door might be locked, the floor might hide a deadly trap, or some other circumstance might make it challenging for an adventurer to complete a task. In those cases, the GM decides what happens, often relying on the roll of a die to determine the results of an action.  <div style='margin-top:10px'></div>
3. **The GM narrates the results of the adventurers’ actions.** Describing the results often leads to another decision point, which brings the flow of the game right back to step 1. <div style='margin-top:1px'></div>

This pattern holds whether the adventurers are cautiously exploring a ruin, talking to a devious prince, or locked in mortal combat against a might dragon. In certain situations, particularly combat, the action is more structured and the players and the GM do take turns choosing and resolving actions. But most of the time, play is fluid and flexible, adapting to the circumstances of the adventure.  <div style='margin-top:1px'></div>

Often the action of an adventure takes place in the imagination of the players and GM, relying on the GM’s verbal descriptions to set the scene. Some GMs like to use music, art, or recorded sound effects to help set the mood, and many players and GMs alike adopt different voices for the various adventurers, monsters, and other characters they play in the game. <div style='margin-top:1px'></div>

Sometimes a GM might lay out a map and use tokens or miniature figures to represent each creature involved in a scene to help the players keep track of where everyone is.<div style='margin-top:1px'></div>

### GAME DICE
<div style='margin-top:1px'></div>

The game uses polyhedral dice with different numbers of sides. You can find dice like these in game stores and in many bookstores.<div style='margin-top:1px'></div>

In these rules, the different dice are referred to by the letter d followed by the number of sides: d4, d6, d8, d10, d12 and d20. For instance, a d6 is a six-sided die (the typical cube that many games use).<div style='margin-top:1px'></div>

Percentile dice, or d100, work a little differently, you generate a number between 1 and 100 by rolling two different ten-sided dice numbered from 0 to 9. One die (designated before you roll) gives the tens digit, and the other gives the ones digit. <div style='margin-top:1px'></div>

If you roll a 7 and a 1, for example, the number rolled is 71. Two 0’s represent 100. Some ten-sided dice are numbered in tens (00, 10, 20, and so on), making it easier to distinguish the tens digit from the ones digit. In this case, a roll of 70 and 1 is 71, and 00 and 0 is 100.<div style='margin-top:1px'></div>

When you need to roll dice, the rules tell you how many dice to roll of a certain type, as well as what modifiers to add. For example, “3d8+5” means you roll three eight sided-dice, add them together, and add 5 to the total.<div style='margin-top:1px'></div>

The same d notation appears in the expressions “1d3” and “1d2”. To simulate the roll of 1d3, roll a d6 and divide the number rolled by 2 (round up). To simulate the roll of 1d2, roll any die and assign a 1 or 2 to the roll depending on whether it was odd or even. (Alternatively, if the number rolled is more than half the number of sides on the die, it’s a 2.)<div style='margin-top:1px'></div>

### THE D20

Does an adventurer’s sword swing hurt a dragon or just bounce off its iron-hard scales? Will the ogre believe an outrageous bluff? Can a character swim across a raging river? Can a character avoid the main blast of a fireball, or does he or she take full damage from the blaze? In cases where the outcome of an action is uncertain, the game relies on rolls of a 20-sided die, a d20, to determine success or failure.<div style='margin-top:1px'></div>

Every character and monster in the game has capabilities defined by six ability scores. The abilities are Strength, Dexterity, Constitution, Intelligence, Wisdom, and Charisma, and they typically range from 3-18 for most adventurers. (Monsters might have scores as low as 1 or as high as 30). These ability scores, and the ability modifiers derived from them, are the basis for almost every d20 roll that a player makes on a character’s or monster’s behalf.<div style='margin-top:1px'></div>

Ability checks, attack rolls, and saving throws are the three main kinds of d20 rolls, forming the core of the rules of the game. All three follow these simple steps.<div style='margin-top:1px'></div>
1. **Roll the die and add a modifier**. Roll a d20 and add the relevant modifier. This is typically the modifier derived from one of the six ability scores, and it sometimes includes a proficiency bonus to reflect a character’s particular skill. (See chapter 1 for details on each ability and how to determine an ability’s modifier.)
2. **Apply circumstantial bonuses and penalties.** A class feature, a particular skill or some other effect might give a bonus or penalty to the check. 
3. **Compare the total to a target number.** If the total equals or exceeds the target number, the ability check, attack roll, or saving throw is a success. Otherwise, it’s a failure. The GM is usually the one who determines target numbers and tells players whether their ability checks, attack rolls and saving throws succeed or fail. 
	 
<div class='pageNumber auto'></div>

\page
<div style='margin-top:1px'></div>

The Target number for an ability check or a saving throw is calla **Difficulty Check (DC)**. The target number for an attack roll is called an **Armor Class (AC)**.<div style='margin-top:1px'></div>

This simple rule governs the resolution of most tasks in the game. Chapter 7 provides more detailed rules for using the d20 in the game.<div style='margin-top:1px'></div>
   
### ADVANTAGES AND DISADVANTAGES	
<div style='margin-top:1px'></div>

Sometimes an ability check, attack roll, or saving throw is modified by special situations called advantage and disadvantage. Advantage reflects the positive circumstances surrounding a d20 roll, while disadvantage reflects the opposite. When you have either advantage or disadvantage, you roll a second d20 when you make the roll. Use the higher of the two rolls if you have advantage, and use the lower roll if you have disadvantage. For example, if you have disadvantage and roll a 17 and a 5, you use the 5. If you instead have advantage and roll those numbers, you use the 17. <div style='margin-top:1px'></div>

More detailed rules for advantage and disadvantage are presented in Chapter 7.<div style='margin-top:1px'></div>

### SPECIFIC BEATS GENERAL<div style='margin-top:1px'></div>

This book contains rules, especially in parts 2 and 3, which govern how the game plays. That said, many racial traits, combat arts and meta arts, magic items, monster abilities and other game elements break the general rules in some way. Remember this: If a specific rule contradicts a general rule, the specific rule wins.<div style='margin-top:1px'></div> 
### ROUND DOWN
There’s one more general rule you need to know at the outset. Whenever you divide a number in the game, round down if you end up with a fraction, even if the fraction is one-half or greater. 

### ADVENTURES<div style='margin-top:1px'></div>

The game consists of a group of characters embarking on an adventure that the GM presents to them. Each character brings particular capabilities to the adventure in the form of ability scores and skill, class features, racial traits, equipment and magic items. Every character is different, with various strengths and weaknesses, so the best party of adventurers is one in which the characters complement each other and cover the weaknesses of their companions. The adventurers must cooperate to successfully complete the adventure. <div style='margin-top:1px'></div>
<img 
  src='http://vignette4.wikia.nocookie.net/dragons/images/b/b9/Nefermandias.png/revision/latest/scale-to-width-down/640?cb=20100401225608' 
  style='width:230px' />
  
The adventure is the heart of the game, a story with a beginning, a middle and an end. An adventure might be created by the GM or purchased off the shelf, tweaked and modified to suit the GM’s needs and desires. In either case, an adventure features a fantastic setting, whether it’s an underground dungeon, a crumbling castle, a stretch of wilderness, or a bustling city. It features a rich cast of characters; the adventurers created and played by the other players at the table, as well as non-player characters (NPCs). Those characters might be patrons, allies, enemies, hirelings, or just background extras in an adventure. Often, one of the NPCs is a villain whose agenda drives much of an adventure’s action.<div style='margin-top:1px'></div>

Over the course of their adventures, the characters are confronted by a variety of creatures, objects, and situations that they must deal with in some way. Sometimes the adventurers and other creatures do their best to kill or capture each other in combat. At other times, the adventurers talk to another creature (or even a magical object) with a goal in mind. And often, the adventurers spend time trying to solve a puzzle, bypass an obstacle, find something hidden, or unravel the current situation. Meanwhile, the adventurers explore the world, making decisions about which way to travel and what they’ll try to do next. <div style='margin-top:1px'></div>

Adventures vary in length and complexity. A short adventure might present only a few challenges, and it might take no more than a single game session to complete. A long adventure can involve hundreds of combats, interactions, and other challenges, and take dozens of sessions to play through, stretching over weeks or months of real time. Usually, the end of an adventure is marked by the adventurers heading back to civilization to rest and enjoy the spoils of their labors.<div style='margin-top:1px'></div>

But that’s not the end of the story. You can think of an adventure as a single episode of a TV series, made up of multiple exciting scenes. A campaign is the whole series – a string of adventures joined together, with a consistent group of adventurers following the narrative from start to finish.<div style='margin-top:1px'></div>

<img 
  src='https://i0.wp.com/www.terminally-incoherent.com/blog/wp-content/uploads/2012/10/merchant.png' 
  style='width:325px' />

\page

### THE THREE PILLARS OF ADVENTURE
Adventurers can try to do anything their players can imagine, but it can be helpful to talk about their activities in three broad categories: exploration, social interaction and combat. <div style='margin-top:1px'></div>

Exploration includes both the adventurers’ movement throughout the world and their interaction with objects and situations that require their attention. Exploration is the give-and-take of the players describing what they want their characters to do, and the GM telling the players what happens as a result. ON a large scale, that might involve the characters spending a day crossing a rolling plain or an hour making their way through caverns underground. On the smallest scale, it could mean one character pulling a lever in a dungeon room to see what happens.
	Social interaction features the adventurers talking to someone (or something) else. It might mean demanding that a captured scout reveal the secret entrance to the goblin lair, getting information from a rescued prisoner, pleading for mercy from an orc chieftain, or persuading a talkative magic mirror to show a distant location to the adventurers. 
	The rules in chapters 7 and 8 support exploration and social interaction, as do many class features in chapter 3 and personality traits in chapter 4.
	Combat, the focus of chapter 9, involves characters and other creatures swinging weapons, casting spells, maneuvering for position, and so on – all in an effort to defeat their opponents, whether that means killing every enemy, taking captives, or forcing a rout. Combat is the most structured element of a gaming session, with creatures taking turns to make sure that everyone gets a chance to act. Even in the context of a pitched battle, there’s still  plenty of opportunity for adventurers to attempt wacky stunts like surfing down a flight of stairs on a shield, to examine the environment (perhaps by pulling a mysterious lever), and to interact with other creatures, including allies, enemies and neutral parties.

META ARTS
Magic within the realms of Ashenguarde manifests itself in what is known as Meta Arts. These arts are divided by many different categories that can be found in chapters 10 and 11.
	In the realms of Ashenguarde, practitioners of the Meta Arts are rare, set apart from the masses of people by their extraordinary talent. Common folk might see evidence of this on a regular basis, but it’s usually minor – a fantastic monster, a visibly answered prayer, a wizard walking through the streets with an animated shield guardian as a bodyguard.
	 For adventurers, though the Meta Arts is key to their survival. Without the healing energies of clerics and paladins, adventurers would quickly succumb to their wounds. Without the uplifting magical support of bards and clerics, warriors might be overwhelmed by powerful foes. Without the sheer supernatural power and versatility of wizards and druids, ever thereat would be magnified tenfold. 
	The Meta Arts is also a favored tool of villains. Many adventurers are driven by the machinations of spellcasters who are hellbent on using these powers for some ill end. A cult leader seeks to awaken a god who slumbers beneath the sea, a hag kidnaps youths to magically drain them of their vigor, a mad wizard labors to invest an army of automatons with a facsimile of life, a dragon begins a mystical ritual to rise up as a god of destruction – these are just a few of the magical threats that adventurers might face. With access to the Meta Arts of their own, in the form of spells and magic items, the adventurers might prevail!

	
	

  
  

</pre></code></details>

**Comment by calculuschild** [comment] 2018-04-17 12:11
I believe this was a duplicate of #655 .

In any case, I am closing this because the brew has since been deleted.

**Closed by calculuschild** 2018-04-17 12:11 UTC
Labels: duplicate
