### ISSUE TITLE
"Class Features" error

### ISSUE THREAD

**Issue by jbdryden** [stolksdorf/homebrewery#357] opened 2017-03-11 02:17 UTC
When I try to add the "Class Features" pre-generated material, it keeps populating it in multiple places throughout the document and creating other coding problems.

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment] 2018-05-10 18:10
Duplicate of #413 . A fix is on the way.

**Closed by calculuschild** 2018-05-10 18:10 UTC
Labels: duplicate
