### ISSUE TITLE
Deleted brews still appearing in "Recent" section

### ISSUE THREAD

**Issue by sIllverback** [stolksdorf/homebrewery#323] opened 2017-02-03 00:07 UTC
It's me again. A few months ago, I suggested removing any deleted brews from the "recent" section. It was implemented and worked correctly, but I think with the update that introduced the metadata and introduced profiles, it may not be working anymore.

Not for me, at least. I deleted a brew and it still appears in my "recent" tab, even when attempting to visit it after deleting it.

You fixed it once, so I wanted to bring it to your attention just in case something went wrong.

EDIT: Looks like it might actually just be something with the "recent" brews tab itself. I updated one of my older brews, and while my profile shows that I had updated it recently, the "recent" tab still shows the time of my last edit as several months ago (actual content is still edited, the time stamp just isn't updated).

**Comment by calculuschild** [comment] 2018-04-21 23:57
Duplicate of #577

**Closed by calculuschild** 2018-04-21 23:57 UTC
