### ISSUE TITLE
brewRenderer Height set to 0 on brew reload

### ISSUE THREAD

**Issue by JordPWN** [stolksdorf/homebrewery#499] opened 2017-09-25 02:13 UTC
When reloading a previously written brew, the brewRenderer initializes with a height of 0. Also, the code editor isn't visible, but I can't isolate precisely why.
<img width="1440" alt="screen shot 2017-09-24 at 10 12 25 pm" src="https://user-images.githubusercontent.com/8186604/30789744-9825aec0-a175-11e7-96e4-60225327b4d1.png">

**Comment by JordPWN** [comment] 2017-09-25 13:29
Additionally, the other issue is related to no content being loaded to the DOM, as seen here:
<img width="796" alt="screen shot 2017-09-25 at 9 29 31 am" src="https://user-images.githubusercontent.com/8186604/30810750-13a2ea28-a1d4-11e7-8bf2-8e7a066fe054.png">

**Comment by calculuschild** [comment] 2017-09-25 14:14
This is the same as about 90% of other issues listed here. You have entered
some invalid HTML code and saved it while it was invalid. This causes the
rendering system to crash.

If you can't get to your code, you can at least go to the "share" button on
the top right, then "view source", copy your code, make a new brew, fix
your code, then save. You can then delete your old brew through your
account page.

**Comment by JordPWN** [comment] 2017-09-27 13:38
Thanks @calculuschild. I guess that's the danger of formatting HTML.

**Comment by calculuschild** [comment] 2018-04-21 23:54
Duplicate of #655

**Closed by calculuschild** 2018-04-21 23:54 UTC
