### ISSUE TITLE
Save to PDF in Chrome duplicates stat headings

### ISSUE THREAD

**Issue by dpmcalister** [stolksdorf/homebrewery#382] opened 2017-04-17 20:57 UTC
Firstly, thanks for this brilliant resource!

I'm putting together character sheets for a convention game this weekend and have come across an issue. Basically, everything looks good until I go to Save to PDF (in Chrome v57.0.2987.133 (64-bit)). Then the stat headings (STR, DEX, CON, INT, WIS, CHA) are duplicated with the second overlapping the actual numbers. I've played around with the scaling in Chromes Save to PDF settings and when I reduce the scale to 97 they disappear again but that introduces other layout issues. I think the issues might be caused because I'm using the A4 snippet but I can't be sure.

Any help would be gratefully received. Thanks.

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/HkBr9mP-0g

**Comment by JosoIce** [comment] 2017-04-20 10:53
I'm having a similar issue with the class table where the column headings duplicate lower down, covering text.

![class table](https://cloud.githubusercontent.com/assets/27810518/25227325/68b8287e-260b-11e7-93c8-b40f30074901.png)

**Comment by mlenser** [comment] 2017-07-20 19:07
I'm having the same issues.

**Comment by HeruAsatru** [comment] 2017-11-15 17:10
Sorry for the necromancy, but...

This is a Chrome problem, not a homebrewery problem. 

You can fix it by adding 
`<style>  
@media print {
    thead {
        display: table-row-group;
    }
}
</style>
`

at the top of your brew.

**Comment by mlenser** [comment] 2017-11-15 20:34
I fixed it by moving my tables to the bottom of each page, but that's awesome. Thanks for sharing!

**Comment by calculuschild** [comment] 2018-04-10 15:28
Duplicate of #318

**Closed by calculuschild** 2018-04-10 15:28 UTC
Labels: duplicate
