### ISSUE TITLE
Problem with table rendering

### ISSUE THREAD

**Issue by Andyrgreig** [stolksdorf/homebrewery#642] opened 2018-03-25 19:25 UTC
Hi,

I'm new to Homebrewery and I'm having a problem with inconsistent table rendering.  Most of the tables in my document render perfectly when I save as PDF, but a couple end up like the attached image.  

I have no idea what the problem is.  Any help or suggestions would be greatly appreciated!

![exhaustion](https://user-images.githubusercontent.com/37780199/37879046-e843ae06-3069-11e8-971b-e67279861ffd.png)

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

##### Exhaustion
| Level | Effect |
|:----:|:-------------|
| 1  | Speed halved |
| 2  | Disadvantage on attack rolls and saving throws |
| 3 | Disadvantage on ability checks |
| 4 | Hit point maximum halved |
| 5 | Speed reduced to 0 |
| 6 | Death |

</pre></code></details>

**Comment by calculuschild** [comment] 2018-04-10 13:44
Look at #318. There is a solution.

Duplicate of #318

**Closed by calculuschild** 2018-04-10 13:44 UTC
