### ISSUE TITLE
PDF Saving/Print Problems

### ISSUE THREAD

**Issue by thecrazygamer25** [stolksdorf/homebrewery#659] opened 2018-04-15 01:47 UTC
Having an issue with printing. Picture provided since its hard to explain
![capture](https://user-images.githubusercontent.com/38389694/38774082-15684482-4014-11e8-8966-f05f5c0ddd5e.PNG)

**Comment by thecrazygamer25** [comment] 2018-04-15 01:48
Note: It looks as it should for everything else just not the pdf

**Comment by calculuschild** [comment] 2018-04-15 02:44
This is a known issue, but there is a workaround until we get it fixed. See #318.

Duplicate of #318.

**Closed** 2018-04-15 02:45 UTC
Labels: duplicate
