### ISSUE TITLE
Issues with format bellow class table

### ISSUE THREAD

**Issue by PalaNolho** [stolksdorf/homebrewery#400] opened 2017-05-11 19:24 UTC
Since some weeks ago, I started to notice some issues with the text format bellow class tables.

here is an example: http://homebrewery.naturalcrit.com/edit/H1fy3zGrJZ

![image](https://cloud.githubusercontent.com/assets/6009914/25967895/8f49653e-3687-11e7-86c5-e18022732303.png)

**Comment by jimcullenaus** [comment] 2017-05-21 18:12
I also have this issue frequently. I've found it will fix itself (temporarily, at least) if you just add and then immediately remove a couple of characters right after the table. I just did that with your edit link, and currently it's displaying correctly.

It seemingly randomly switches back to the broken formatting after a while, though.

**Comment by jimcullenaus** [comment] 2017-05-22 10:19
Duplicate of #295.

**Comment by 3v3rl0st** [comment] 2017-05-31 01:17
i've had that too. If it doesn't fix itself w/ a page refresh i've also added a <br> after the table to add a space.

**Closed** 2018-04-11 00:48 UTC
