### ISSUE TITLE
Column Break Doesn't Work

### ISSUE THREAD

**Issue by IGJoshua** [stolksdorf/homebrewery#543] opened 2017-11-02 22:56 UTC
So it seems like the column break isn't doing what it's supposed to do. And by that I mean it's not doing anything.

Perfect example is the first page when you first open it up. The line saying `Big things coming in v3.0.0` should appear on the right column, but it doesn't.

### Additional Details

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

Some test text.

\`\`\`
\`\`\`

Some more test text.

</pre></code></details>

**Comment by IGJoshua** [comment] 2017-11-03 00:26
I've since discovered that this issue exists primarily in FireFox. Everything works as expected in Google Chrome.

**Comment by calculuschild** [comment] 2017-11-03 01:43
That makes sense, since only Chrome is supported.

**Comment by PadgeM** [comment] 2017-11-18 04:27
I'm running Chrome and it's not working for me.  It does the column break but it ends up destroying the note behind it.

**Comment by calculuschild** [comment] 2018-04-11 16:51
@PadgeM Do you still notice this issue? Do you have a specific code example or screenshot? I am unable to reproduce this problem and will be closing the issue unless we hear more.

**Closed by calculuschild** 2018-04-11 16:51 UTC
