### ISSUE TITLE
Need help exporting to PDF - only first page gets done

### ISSUE THREAD

**Issue by Ziggycan** [stolksdorf/homebrewery#187] opened 2016-09-06 00:05 UTC
Hey there - great tool.

I have created a 40 page document - then reduced it to a few pages but i cannot seem to get it to export to PDF - (I have tried the suggestions). I am an old school MF programmer/DBA who has been promoted to management and not as savvy with the new stuff as I should be :) If you want the code let me know - here is the view page  - i just didnt want to go overboard right away.

http://homebrewery.naturalcrit.com/share/SkY0K12t

Thanks in advance - Joel.

**Comment by stolksdorf** [comment] 2016-09-07 13:21
Sorry for the delay Joel! The issue is really easy to fix. You have a few opening `div` tags without closing ones. The print view is not as forgiving with mismatched div tags, hence why you are getting this issue.

Your first page actually has _a lot_ of custom HTML going on, and I think it's the root of the issue. 

- The `font` tag has become deprecated in HTML5, so it's support is pretty shaky. I would suggest not using that. 
- You also do not need to separate element properties by semi-colons, jut spaces will do. 
- When in doubt try to use less spacing divs and let the layout work for you. 

Here are some suggestions to improve that opening page code-wise

```
<div class='wide'>

# Zendikar Campaign
##### Source material

- http://mtgsalvation.gamepedia.com/
- http://media.wizards.com/2016/downloads/magic/Plane%20Shift%20Zendikar.pdf
- http://magic.wizards.com/en/articles/archive/arcana/announcing-art-magic-gathering-zendikar-2015-08-3

##### Images are credited where known.

<div style='margin-top:40px'></div>


##### Maps were created on Campaign Cartographer Pro
https://secure.profantasy.com/default.asp

##### Players handbook Formatting by The Homebrewery
http://homebrewery.naturalcrit.com/

##### Adventure Ideas - 1 sessions adventures based of the '5 Room Dungeon'
http://roleplayingtips.com/readissue.php?number=156

##### CCG Cards created by Magic Set Editor 2
http://magicseteditor.sourceforge.net/
</div>
```

Or like this, where I used hyperlinks to clean it up even further

```
<div class='wide'>

# Zendikar Campaign

<div style='margin-top:40px'></div>


### References
##### Source material

- http://mtgsalvation.gamepedia.com/
- http://media.wizards.com/2016/downloads/magic/Plane%20Shift%20Zendikar.pdf
- http://magic.wizards.com/en/articles/archive/arcana/announcing-art-magic-gathering-zendikar-2015-08-3

*Images are credited where known.


##### Maps were created on [Campaign Cartographer Pro](https://secure.profantasy.com/default.asp)

##### Players handbook Formatting by [The Homebrewery](http://homebrewery.naturalcrit.com/)

##### Adventure Ideas - 1 sessions adventures based of [the '5 Room Dungeon'](http://roleplayingtips.com/readissue.php?number=156)

##### CCG Cards created by [Magic Set Editor 2](http://magicseteditor.sourceforge.net/)

</div>
```


Hope that helps!

**Closed by stolksdorf** 2016-09-07 13:21 UTC

**Comment by Ziggycan** [comment] 2016-09-07 17:52
Awesome! Thanks will try that this evening!

Joel Zigelstein
