### ISSUE TITLE
Class table no longer separates from text columns properly?

### ISSUE THREAD

**Issue by CaptDeathCap** [stolksdorf/homebrewery#336] opened 2017-02-12 23:48 UTC
--> http://prnt.sc/e7ym6v <--
This suddenly happened to all my class tables. Friends reported the issue to me, so it's not just on my end. Is a fix known? The brews are from an older version of homebrewery, so I suspect some dated code issues.

### Additional Details

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>
<div class='classTable wide'>
##### The Earth Seer

| Level | Proficiency Bonus | Stone Strokes |Features | Ki Points |Cantrips Known| Spells Known |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| 1st | +2 | 1d4 | Earth's Fortitude, Stone Strokes | - | - | - |
| 2nd | +2 | 1d4 | Ki | 2 | 2 | 2 ( 1st lvl ) |
| 3rd | +2 | 1d4 | Seer Structure | 3 | 2 | 2 ( 2nd lvl ) |
| 4th | +2 | 1d6 | Ability Score Improvement | 4 | 2 | 3 ( 2nd lvl ) | 
| 5th | +3 | 1d6 | Terrene Athlete | 5 | 3 | 3 ( 3rd lvl ) |
| 6th | +3 | 1d6 | Seer Structure Feature | 6 | 3 | 4 ( 3rd lvl ) |
| 7th | +3 | 1d8 | Elemental Understanding | 7 | 3 | 4 ( 4th lvl ) |
| 8th | +3 | 1d8 | Ability Score Improvement | 8 | 3 | 5 ( 4th lvl ) |
| 9th | +4 | 1d8 | Seismic Strikes | 9 | 3 | 5 ( 5th lvl ) |
| 10th | +4 | 1d8 | Tremorsense | 10 | 3 | 6 ( 5th lvl ) |
| 11th | +4 | 1d8 | Seer Structure Feature | 11 | 4 | 6 ( 6th lvl ) |
| 12th | +4 | 1d10 | Ability Score Improvement | 12 | 4 | 7 ( 6th lvl ) |
| 13th | +5 | 1d10 | Heightened Focus | 13 | 4 | 7 ( 7th lvl ) |
| 14th | +5 | 1d10 | Improved Earth's Fortitude | 14 | 4 | 8 ( 7th lvl ) |
| 15th | +5 | 1d10 | Timeless Body | 15 | 4 | 8 ( 8th lvl ) |
| 16th | +5 | 1d10 | Ability Score Improvement | 16 | 4 | 9 ( 8th lvl ) |
| 17th | +6 | 1d10 | Seer Structure Feature | 17 | 4 | 9 ( 9th lvl ) |
| 18th | +6 | 1d12 | Gravity Weaver | 18 | 4 | 10 ( 9th lvl ) |
| 19th | +6 | 1d12 | Ability Score Improvement | 19 | 4 | 10 ( 9th lvl ) |
| 20th | +6 | 1d12 | Planar Fissure Strike | 20 | 4 | 10 ( 9th lvl )|

</div>
##### Class Features
As an Earth Seer, you gain the following features.
<br>
### Hit Points<br>
**Hit Dice:** 1d8 per Earth Seer level.<br>
**Hit Points at 1st level:** 8 + your Constitution modifier<br>
**Hit Points at Higher Levels:** 1d8 (or 5) + your Constitution modifier per Earth Seer level after 1st

### Proficiencies
**Armor:** Light Armor<br>
**Weapons:** Daggers, Shortswords, Quarterstaffs, Slings<br>
**Tools:** (a) Jeweler's Tools or, (b) Mason's Tools<br><br>
**Saving Throws:** Strength, Wisdom<br>
**Skills:** Choose two from Acrobatics, Athletics, History, Insight, Religion, Nature, and Survival.

### Equipment
You start with the following equipment, in addition to the equipment granted by your background:
* (a) a quarterstaff, or (b) a shortsword
* (a) a sling, or (b) two daggers
* (a) a dungeoneer's pack or (b) an explorer's pack
* Leather armor

### Earth's Fortitude
Your innate connection to the earth increases your resilience.
While your are wearing no armor and not wielding a shield, your AC equals 10 + your Dexterity modifier + your Constitution modifier.

Additionally, if you are wearing Light armor, your Constitution modifier may replace your Dexterity modifier when calculating your AC.

### Stone Strokes
Starting at 1st level, you may spend a bonus action to coat your limbs in nearby rock, giving you 2 'Stone Strokes' charges.
You may take this bonus action once, and must complete a short or long rest to use it again.

So long as you have at least 1 charge available, you can roll a d4 in place of the normal damage of your unarmed strikes.

This die changes as you gain Earth Seer levels, as shown in the Stone Strokes column of the Earth Seer table.

Additionally, whenever you hit a creature with a spell or unarmed strike, you may expend one or two charges and add their respective damage dice to the damage total as bludgeoning damage. 
<div class='pageNumber'>1</div>
<div class='footnote'>Earth Seer</div>
\page

### Ki
Starting at 2nd level, in similar ways to a monk, your connection to the earth allows you to harness the mystical energy of ki. Your access to this energy is represented by a number of ki points. Your Earth Seer level determines the number of points you have, as shown in the Ki Points column of the Earth Seer table.

You can spend these points to fuel various ki features.<br> You start knowing three such features: Refresh and two earth seer spells.

When you spend a ki point, it is unavailable until you finish a short or long rest, at the end of which you draw all of your expended ki back into yourself. You must spend at least 30 minutes of the rest meditating to regain your ki points.

##### Refresh
You may spend 1 ki points to manifest your stone strokes, without the need to complete a short rest.

##### Cantrips
Starting at 2nd level, you know two cantrips of your choice from the earth seer spell list. You learn additional earth seer cantrips of your choice at higher levels, as shown in the Cantrips Known column of the Earth Seer table.

##### Spells Known of 1st Level and Higher
From 2nd level onward, you know two 1st-level spells of your choice from the earth seer spell list.
The Spells Known column of the Earth Seer table shows when you learn more earth seer spells of your choice. The maximum spell level for these spells is shown between parentheses. Additionally, when you gain a level in this class, you can choose one of the earth seer spells you know and replace it with another spell from the earth seer spell list, which must also be equal or lower to your maximum spell level.

##### Casting Earth  Seer Spells
Unlike other classes adept in the use of magic, Earth Seers (and monks trained in the Way of the Four Elements) tap into their ki to bring forth magic. To cast a spell, you use its casting time and other rules, but you don't need to provide material components unless they have a listed price.
Casting a spell expends ki points equal to the spell level + 1.

Cantrips require no ki point to cast.

When you use ki to cast a spell of 6th level or higher, you must complete a long rest before you can cast another spell of the same spell level.

<div class='pageNumber'>2</div>
<div class='footnote'>Earth Seer</div>

##### Spellcasting Ability
Wisdom is your spellcasting ability for your Earth Seer spells, as your magic draws upon your connection to- and the understanding of the very earth itself. You use your Wisdom whenever a spell or class feature refers to your spellcasting ability. In addition, you use your Wisdom modifier when setting the saving throw DC for an earth seer features and spells you cast and when making an attack roll with them.
<br><br>
<center>**Spell save DC** = 8 + your proficiency bonus +<br> your Wisdom modifier
<br><br>
**Spell attack modifier** = your proficiency bonus + <br>your Wisdom modifier</center>
```
```

### Seer Structure
At 3rd level, you choose to identify with a Seer Structure: the Structure of Sand, the Structure of Soil or the Structure of Stone, all detailed at the end of the class description. Your choice grants you features at 3rd level and again at 6th, 11th and 17th level.

### Ability Score Improvement
When you reach 4th level, and again at 8th, 12th, 16th, and 19th level, you can increase one ability score of your choice by 2, or you can increase two ability scores of your choice by 1. As normal, you can’t increase an ability score above 20 using this feature.

### Terrene Athlete
At 5th level, you have learned to empower your feats of athletics by moving the earth beneath your feet to propel you. So long as you are touching rock or earth, your walking speed (and burrowing speed if applicable) increases by 10 and you are always considered to have a running start when jumping. Additionally, if grounded, you may spend 1 ki point to take the Dash action as a bonus action.

### Elemental Understanding
Starting at 7th level, you may spend a ki point to speak with rocks and earth related golems as if you shared a language, for up to 10 minutes. Additionally, you learn to speak and write the Primordial language.

### Seismic Strikes
Starting at 9th level, your unarmed strikes are considered to deal both Bludgeoning damage and Thunder damage simultaneously, so long as you have at least one active charge of stone strokes. A creature that resists one, but not both types of damage takes damage as if it had no resistance to either. If both types are resisted, resistance is applied as normal.

### Tremorsense
Starting at 10th level, your connection with the earth has become strong to the point where you can sense its very vibrations. You gain tremorsense, allowing you to detect any corporeal grounded or burrowing creature within a range of 30 feet, or 60 feet if your skin is directly in contact with the ground. A creature that spends its turn without disturbing the earth cannot be detected in this fashion.

### Heightened Focus
Starting at 13th level, whenever you manifest your Stone Strokes, you may expend 2 ki points to gain 2 additional Stone Strokes charges.
\page

### Improved Earth's Fortitude
From 14th level onward, your body has adapted to resist even the most potent of poisons. You resist poison damage and you have advantage on Constitution saving throws to resist poison.

### Timeless Body
At 15th level, your ki sustains you so that you suffer none of the frailty of old age, and you can't be aged magically. You can still die of old age, however. In addition, you no longer need food or water.

### Gravity Weaver
Starting at 18th level, you have learned to manipulate your personal gravitational influence. Once per short rest, you may take an action to impose a Strength saving throw on all creatures within 30 feet. Choose one of the effects below. All creatures that fail the save take 3d6 Force damage and suffer the effect.

**Gravitation.** Affected creatures are moved 10 feet directly towards you.

**Repulsion.** Affected creatures are moved 10 feet directly away from you.

### Planar Fissure Strike
At 20th level, your connection to the earth has become so powerful, your attacks tear rifts to and from the elemental plane of Earth. Whenever you hit a creature with a spell attack or unarmed strike, you may expend a charge of stone strokes to deal an additional 4d12 Force damage as part of the attack. Additionally, if the attack reduces the target to 50 hit points or less, you banish it to the elemental plane of Earth. A creature that is already on this plane instead vanishes into a harmless demiplane. While there, the target is incapacitated. It remains there for 1 minute, before it reappears in the space it left, or in the nearest unoccupied space if that space is occupied.

You must complete a long rest before you can use this feature again.
```
```

##### Seer Structures
Three Structures of Earth Seers exist throughout the multiverse. Each harbors seers that specialize in its respective field of expertise, though conclaves of all three structures are hosted sporadically, to discuss discoveries or issues with one another, or share pleasantries. All three structures share the same foundations, allowing their students to be schooled together until it is time for them to dedicate themselves to a particular structure.

### the Structure of Sand
Seers of the Structure of Sand focus on discovering the mysteries within the depths of the sands. Most live a nomadic life in deserts, though some spend time on the ocean floor, in search of treasures of both wealth and knowledge.

##### Scorpion's Sting
Starting when you choose this Structure at 3rd level, whenever you take the attack action, you may make one unarmed strike as a bonus action. The attack may use your Stone Strokes damage die, even if you expended your last charge taking the prior attack action.

##### Ambush Predator
At 6th level, you gain a burrowing speed of 30 feet. In addition, whenever you burrow 20 feet straight toward a target right before hitting it with a melee weapon attack, the target must succeed a Strength saving throw or be knocked prone. A creature you have surprised has disadvantage on the saving throw.
##### Sidewinder
At 11th level, you can instinctually navigate deserts and other large masses of sand. Traveling in arid environments does not cause you to gain levels of exhaustion and you gain advantage on Wisdom (Survival) checks when trying to navigate the desert. Additionally, you can always tell the time, and which way is north, from the position of the sun and moon.

##### Kurara's Wrath
Starting at 17th level, You may take an action to cast Sand Storm at 9th level without expending ki points. You must finish a long rest before you can use this feature again.
<div class='pageNumber'>3</div>
<div class='footnote'>Earth Seer</div>
\page

### the Structure of Soil
Those that join the Structure of Soil often do so to better understand and control the earth. Members of this structure often go out of their way to uphold balance in the universe, and their fighting style of weaving in spells between strikes reflects this.

##### Ki Efficiency
Starting when you choose this structure at 3rd, and again at 6th and 11th level, your maximum amount of spells known increases by 1. In addition, whenever you take an action to attack or cast a spell, you may spend 1 ki point to cast a cantrip from the earth seer spell list as a bonus action.

##### Arcane Disruption
From 6th level onward, you may choose to expend 2 additional ki points whenever you cast a spell that can deal damage. Choose 1 creature affected by the spell. The excess arcane energy lingers within its body for up to 1 hour. If the creature casts a spell or is hit by a melee weapon attack, the arcane energy detonates. The creature takes Force damage equal to 3 x your stone strokes damage die and must make a Constitution saving throw. If it fails the saving throw, it is also stunned until the end of your next turn.

If it succeeds the saving throw, it becomes immune to the stun effect until it completes a long rest.

##### Arcane Overdrive
At 11th level, you have learned to use your ki at maximum efficiency, relaying the excess energy straight to your muscles. Once per turn, if you spend ki to cast a spell, your speed increases by 10 feet and you suffer no movement penalty when traversing difficult terrain. This effect lasts until the end of your turn.

##### Orbital Reach
Starting at 17th level, you have become so adept at manipulating the earth, your influence stretches even beyond the atmosphere.
You gain access to the Meteor Swarm spell. This spell does not count towards your amount of spells known.

<div style='margin-bottom:140px'></div>

> ##### Multiclassing Prerequisites
> Wisdom 13
> 
> ##### Multiclassing Proficiencies
> (a) Jeweler's Tools or, (b) Mason's Tools
>
> ##### Optional: Starting Wealth
> 2d4 x 10 gp

```
```
### the Structure of Stone
Seers of the Structure of Stone are renowned for their expert stonework and gem cutting. Artisans live as clans, in large, beautiful bastions and castles. Others roam the land to study stone and precious minerals in the field from within the relative safety of their stone constructs.

#####  Rock Juggernaut
Starting when you choose this Structure at 3rd level, you gain superior control over rock, allowing you to muster up enough material to cover your entire body when you activate your stone strokes feature, increasing your size by 1 stage. This second skin of rock can be made to have whatever appearance you desire. Your rock juggernaut form grants you 16 temporary hit points, + 2 for every earth seer level beyond 3rd level. These hitpoints do not absorb Psychic or Thunder damage. Once the temporary hitpoints are depleted, the form collapses into a small pile of rubble.

Your rock juggernaut form cannot be manifested by activating the Refresh feature.

So long as your rock juggernaut form is active, your more precise movements are restricted, and you cannot provide somatic spell components.

##### Adept Mountaineer
Starting at 6th level, you gain a climb speed of 40, and you make Wisdom (Survival) checks to navigate mountains with advantage.

##### Form Detonation
From 11th level onward, you may take an action to expend all you remaining charges of stone strokes (2 minimum) to have your rock juggernaut form explode. 

Reduce your rock juggernaut hit points to 0. All creatures (except you) in a 15 foot radius must make a Dexterity saving throw. You deal (5 x your stone strokes damage die) bludgeoning damage to all creatures that fail the save, and half this amount to those that succeed. This damage increases by 1 die for every third Earth Seer level beyond the 11th, and for each charge of stone strokes you expended beyond 2.

Additionally, the rubble left behind by the explosion causes the affected area to become difficult terrain until it is cleared.

You may activate Form Detonation whenever your Rock Juggernaut hit points are reduced to 0, without spending an action to do so.

##### Diamond Juggernaut
At 17th level, you have learned how to safely subject your stone outer skin to extreme pressure. You may take an action to compress and harden your Rock Juggernaut form. This grants you resistance to all piercing, bludgeoning and slashing damage, and Psychic- and Thunder damage can no longer bypass your rock juggernaut hit points.

<div class='pageNumber'>4</div>
<div class='footnote'>Earth Seer</div>
\page

##### Cantrips (0 Level)
Druidcraft<br>
Magic Stone<br>
Mending <br>
Minor Illusion <br>
Mold Earth <br>
Resistance <br>
Sword Burst <br>
True Strike 

##### 1st Level
Absorb Elements <br>
Catapult <br>
Detect Magic <br>
Earth Tremor <br>
Ensnaring Strike <br>
Entangle <br>
Feather Fall <br>
Jump <br>
Tenser's Floating Disk

##### 2nd Level
Cloud of Daggers <br>
Dust Devil <br>
Earthbind <br>
Find Traps <br>
Hold Person <br>
Knock <br>
Levitate <br>
Locate Animals or Plants <br>
Maximilian's Earthen Grasp <br>
Rope Trick <br>
Shatter <br>
Spider Climb <br>
Spike Growth

##### 3rd level
Earth Servant <br>
Elemental Weapon <br>
Erupting Earth <br>
Feign Death <br>
Leomund's Tiny Hut <br>
Meld Into Stone <br>
Melf's Minute Meteors <br>
Nondetection <br>
Wall of Sand 

##### 4th Level
Banishment <br>
Blight <br>
Conjure Minor Elementals <br>
Elemental Bane <br>
Fabricate <br>
Freedom of Movement <br>
Hallucinatory Terrain <br>
Sandstorm <br>
Stone Shape <br>
Stoneskin <br>
Mordenkainen's Private Sanctum
```
```
##### 5th Level
Animate Objects <br>
Bigby's Hand <br>
Conjure Elemental <br>
Destructive Wave <br>
Hold Monster <br>
Legend Lore <br>
Passwall <br>
Telekinesis <br>
Transmute Rock <br>
Wall of Stone

##### 6th Level
Blade Barrier <br>
Bones of the Earth <br>
Disintegrate <br>
Find the Path <br>
Flesh to Stone <br>
Investiture of Stone <br>
Move Earth <br>

##### 7th Level
Mirage Arcane <br>
Mordenkainen's Magnificent Mansion <br>
Plane Shift <br>
Reverse Gravity <br>
Sequester <br>

##### 8th Level
Demiplane <br>
Earthquake <br>
Maze <br>
Tsunami <br>

##### 9th level
Astral Projection <br>
Gate <br>
Imprisonment <br>
Meteor Swarm (Exclusive to Structure of Soil)

<div class='pageNumber'>5</div>
<div class='footnote'>Earth Seer</div>

\page
#### Earth Servant
*3rd-level conjuration*
___
- **Casting Time:**  1 minute
- **Range:** 10 feet
- **Components:** V, S, M (A chunk of clay and a drop of water)
- **Duration:** Instantaneous

This spell creates a construct servant. Choose a pile of clay or loose earth. Your spell imbues the target with a mimicry of life, raising it as a construct. The target becomes a Terracotta soldier if you chose clay or a Lesser Golem if you chose earth. (the creature's game statistics are listed later on this page.)
<br><br>
On each of your turns, you can use a bonus action to mentally command any creature you made with this spell if the creature is within 60 feet of you (if you control multiple creatures, you can command any or all of them at the same time, issuing the same command to each one). You decide what action the creature will take and where it will move during its next turn, or you can issue a general command, such as to guard a particular chamber or corridor. If you issue no commands, the creature only defends itself or its creator against hostile creatures. Once given an order, the creature continues to follow it until its task is complete.
<br><br>
The creature is under your control for 24 hours, after which it crumbles to dust. To maintain control of the creature for another 24 hours, you must cast this spell on the creature again before the current 24-hour period ends. This use of the spell reasserts your control over up to four creatures you have animated with this spell, rather than animating a new one.
___
**At Higher Levels.** When you cast this spell using a spell slot of 4th level or higher, you animate or reassert control over two additional constructs for each slot level above 3rd. Each of the creatures must come from a different pile of clay or earth.
<div class='pageNumber'>6</div>
<div class='footnote'>Earth Seer</div>

#### Sandstorm
*4th-level evocation*
___
- **Casting Time:** 1 action
- **Range:** 300 feet
- **Components:** V, S, M (A pinch of sand and a Roc's feather)
- **Duration:** Instantaneous

A dervish of wind and sand ravages the ground in a <br>20-foot-radius, 40-foot-high cylinder centered on a point within range. Each creature in the cylinder must make a Dexterity saving throw. A creature takes 2d8 bludgeoning damage and 4d6 slashing damage on a failed save, or half as much damage on a successful one.

___
a foot of loose sand turns the storm's area of effect into difficult terrain until the end of your next turn.
___
**At Higher Levels.** When you cast this spell using a spell slot of 5th level or higher, the bludgeoning damage increases by 1d8 for each slot above 4th.

```
```
___
> ## Terracotta Soldier
>*Medium Construct, neutral*
> ___
> - **Armor Class** 10
> - **Hit Points** 22 (3d8 + 9)
> - **Speed** 30ft.
>___
>|STR|DEX|CON|INT|WIS|CHA|
>|:---:|:---:|:---:|:---:|:---:|:---:|
>|12 (+1)|10 (+0)|16 (+3)|1 (-5)|1 (-5)|6 (-2)|
>___
> - **Damage Immunities** poison, psychic
> - **Condition Immunities** charmed, exhaustion, frightened, paralyzed, petrified, poisoned
> - **Senses** passive Perception 8
> - **Languages** -
> - **Challenge** 1/4 (50 XP)
> ___
> ***False Appearance. *** While the soldier remains motionless, it is indistinguishable from a statue.
> ### Actions
> ***Spear.*** *Melee Weapon Attack:* +3 to hit, reach 5ft., one target. *Hit* 4 (1d6 + 1) 

___
> ## Lesser Golem
>*Medium Construct, neutral*
> ___
> - **Armor Class** 13 (natural armor)
> - **Hit Points** 25 (3d8 + 12)
> - **Speed** 25ft.
>___
>|STR|DEX|CON|INT|WIS|CHA|
>|:---:|:---:|:---:|:---:|:---:|:---:|
>|15 (+2)|3 (-4)|18 (+4)|1 (-5)|1 (-5)|6 (-2)|
>___
> - **Damage Immunities** poison, psychic
> - **Condition Immunities** charmed, exhaustion, frightened, paralyzed, petrified, poisoned
> - **Senses** passive Perception 5
> - **Languages** -
> - **Challenge** 1/4 (50 XP)
> ___
> ### Actions
> ***Slam.*** *Melee Weapon Attack:* +4 to hit, reach 5ft., one target. *Hit* 5 (1d6 + 2) 

</pre></code></details>

**Comment by CaptDeathCap** [comment] 2017-02-23 01:05
No developments, yet? :( My brews look so ugly now!

**Comment by calculuschild** [comment] 2017-02-23 03:07
Can you provide the share link to your brew? Your code above isn't copying completely for me for some reason. I'll give it a look.

**Comment by CaptDeathCap** [comment] 2017-02-23 19:45
http://homebrewery.naturalcrit.com/share/rJQ-wfSJx

**Comment by calculuschild** [comment] 2017-02-23 20:14
This looks like a duplicate of https://github.com/stolksdorf/homebrewery/issues/291 which was never really solved.

How does it look when it's printed?

**Comment by CaptDeathCap** [comment] 2017-02-23 20:17
Looks exactly the same. It looks fine for a few moments after I mess with it, and during that time, printing it also makes it look fine, but my other brew: http://homebrewery.naturalcrit.com/share/rk8V-o3- doesn't even get fixed for a single moment :/

**Comment by CaptDeathCap** [comment] 2017-02-23 20:43
<div class='classTable wide'>
**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>
##### The Earth Seer

| Level | Proficiency Bonus | Stone Strokes |Features | Ki Points |Cantrips Known| Spells Known |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| 1st | +2 | 1d4 | Earth's Fortitude, Stone Strokes | - | - | - |
| 2nd | +2 | 1d4 | Ki | 2 | 2 | 2 ( 1st lvl ) |
| 3rd | +2 | 1d4 | Seer Structure | 3 | 2 | 2 ( 2nd lvl ) |
| 4th | +2 | 1d6 | Ability Score Improvement | 4 | 2 | 3 ( 2nd lvl ) | 
| 5th | +3 | 1d6 | Terrene Athlete | 5 | 3 | 3 ( 3rd lvl ) |
| 6th | +3 | 1d6 | Seer Structure Feature | 6 | 3 | 4 ( 3rd lvl ) |
| 7th | +3 | 1d8 | Elemental Understanding | 7 | 3 | 4 ( 4th lvl ) |
| 8th | +3 | 1d8 | Ability Score Improvement | 8 | 3 | 5 ( 4th lvl ) |
| 9th | +4 | 1d8 | Seismic Strikes | 9 | 3 | 5 ( 5th lvl ) |
| 10th | +4 | 1d8 | Tremorsense | 10 | 3 | 6 ( 5th lvl ) |
| 11th | +4 | 1d8 | Seer Structure Feature | 11 | 4 | 6 ( 6th lvl ) |
| 12th | +4 | 1d10 | Ability Score Improvement | 12 | 4 | 7 ( 6th lvl ) |
| 13th | +5 | 1d10 | Heightened Focus | 13 | 4 | 7 ( 7th lvl ) |
| 14th | +5 | 1d10 | Improved Earth's Fortitude | 14 | 4 | 8 ( 7th lvl ) |
| 15th | +5 | 1d10 | Timeless Body | 15 | 4 | 8 ( 8th lvl ) |
| 16th | +5 | 1d10 | Ability Score Improvement | 16 | 4 | 9 ( 8th lvl ) |
| 17th | +6 | 1d10 | Seer Structure Feature | 17 | 4 | 9 ( 9th lvl ) |
| 18th | +6 | 1d12 | Gravity Weaver | 18 | 4 | 10 ( 9th lvl ) |
| 19th | +6 | 1d12 | Ability Score Improvement | 19 | 4 | 10 ( 9th lvl ) |
| 20th | +6 | 1d12 | Planar Fissure Strike | 20 | 4 | 10 ( 9th lvl )|
</div>

<div style='margin-top:0px'></div>

##### Class Features</pre></code></details>

**Comment by calculuschild** [comment] 2018-04-11 00:47
Duplicate of #291

**Closed by calculuschild** 2018-04-11 00:47 UTC
