### ISSUE TITLE
Table error when saving as pdf

### ISSUE THREAD

**Issue by ksogard** [stolksdorf/homebrewery#683] opened 2018-05-09 20:14 UTC
*Delete the above section and the instructions in the sections below before submitting*

## Description

"Class tables" and "Descriptive Text Boxes" borders are glitching out when saving as a pdf. See attached images and code below:

![image](https://user-images.githubusercontent.com/39137116/39837192-576eab4c-539b-11e8-80ca-0d3937e260e0.png)

![image](https://user-images.githubusercontent.com/39137116/39837216-6ea9e506-539b-11e8-8fee-2799cbf2068e.png)

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE
<div class='classTable wide'>
##### The Concierge
| Level | Proficiency Bonus | Features | Cantrips Known | Spells Known | 1st | 2nd | 3rd | 4th | 5th | 6th | 7th | 8th | 9th |
|:---:|:---:|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| 1st | +2 | Genetic Banishing | 3 | 1 | 2 | — | — | — | — | — | — | — | — |
| 2nd | +2 | Spiritual Biochemistry | 3 | 1 | 3 | — | — | — | — | — | — | — | — |
| 3rd | +2 | Civil Alchemy | 4 | 2 | 4 | — | — | — | — | — | — | — | — |
| 4th | +2 | Ability Score Improvement, Consecrated Biochemistry | 4 | 3 | 4 | 1 | — | — | — | — | — | — | — |
| 5th | +3 | Seismological Divination | 4 | 3 | 4 | 2 | — | — | — | — | — | — | — |
| 6th | +3 | Ability Score Improvement | 5 | 4 | 4 | 3 | 1 | — | — | — | — | — | — |
| 7th | +3 | Civil Alchemy | 5 | 4 | 4 | 3 | 2 | — | — | — | — | — | — |
| 8th | +3 | Ability Score Improvement, Biochemical Sorcery | 6 | 4 | 4 | 3 | 2 | — | — | — | — | — | — |
| 9th | +4 | Genetic Banishing | 6 | 5 | 4 | 3 | 2 | — | — | — | — | — | — |
| 10th | +4 | ─ | 7 | 5 | 4 | 3 | 2 | — | — | — | — | — | — |
| 11th | +4 | Spell Analyst | 8 | 5 | 4 | 3 | 2 | — | — | — | — | — | — |
| 12th | +4 | Ability Score Improvement, Demonic Anthropology | 9 | 6 | 4 | 3 | 2 | — | — | — | — | — | — |
| 13th | +5 | Exo Interfacer | 10 | 6 | 4 | 3 | 2 | — | — | — | — | — | — |
| 14th | +5 | Ability Score Improvement, Divinatory Mineralogy | 11 | 6 | 4 | 3 | 3 | — | — | — | — | — | — |
| 15th | +5 | Astrological Botany | 11 | 6 | 4 | 3 | 3 | 2 | — | — | — | — | — |
| 16th | +5 | Ability Score Improvement, Orbital Gravedigger | 11 | 6 | 4 | 3 | 3 | 3 | 1 | — | — | — | — |
| 17th | +6 | Spiritual Biochemistry | 11 | 6 | 4 | 3 | 3 | 3 | 2 | — | — | — | — |
| 18th | +6 | Biochemical Sorcery | 11 | 6 | 4 | 3 | 3 | 3 | 3 | — | — | — | — |
| 19th | +6 | Ability Score Improvement, Civil Alchemy | 11 | 6 | 4 | 3 | 3 | 3 | 3 | 1 | — | — | — |
| 20th | +6 | Biochemical Sorcery | 12 | 7 | 4 | 3 | 3 | 3 | 3 | 2 | — | — | — |
</div>

<div class='descriptive'>
##### Time to Drop Knowledge
Use notes to point out some interesting information. 

**Tables and lists** both work within a note.
</div>
</pre></code></details>

**Comment by calculuschild** [comment] 2018-05-10 17:06
Your provided code doesn't cause the issue for me. So, a couple things:

1. Was this on the latest version of Chrome? Other browsers are not supported and may not work as expected.
2. If so, can you provide the **share link** to your document? Maybe something else is going on?

**Comment by ksogard** [comment] 2018-05-10 17:13
Strange. It's doing this for all my documents, even old ones that printed
to pdf properly before. It all looks fine until I click "get pdf" and it
only bugs out within the print screen (see attached). To answer your
questions:

1. This is in the latest version of chrome. I'll try it on another computer
later though.
2. http://homebrewery.naturalcrit.com/share/SyQThgGRz I created this one as
a test.

**Comment by Linix332** [comment] 2018-05-19 11:31
I also seem to be having the same issue. I've tried on 2 different computers. I'm using the latest version of Chrome. My last pdf through "get pdf" that was fine was on the 13th. Noticed the issue for myself 2 days ago, so in my case at least the problem happened between then.

**Comment by Rogkun** [comment] 2018-05-20 06:52
Me and a friend tested this on both homebrewery and GM Binder, with the same issue. (chrome updated, extensions off, separate machines, mine on a fresh install). The default class wide table examples will not work in chrome, at all for us. If it is a user-end issue, it would be a monumental coincidence. This is print preview specific in nature.

**Comment by calculuschild** [comment] 2018-05-20 14:30
I am still unable to reproduce this. Does it only happen with the "wide class table" and "descriptive text box"?

**Comment by Rogkun** [comment] 2018-05-21 11:45
@calculuschild Yes, it occurs with the wide class table (noted as Class table in examples option list) and the descriptive text box. It happens in GM Binder and Homebrewery.

Try it out with another machine to see the effect yourself. In terms of reproducing it otherwise, I have no idea. Again, it seems like a print preview issue specifically with chrome.

What's upsetting is that this renders the class table feature virtually worthless for me. :(
I really like the tables too!

**Comment by AlexeySachkov** [comment] 2018-05-21 12:34
I can reproduce the issue using Version 66.0.3359.181 (Official Build) (32-bit) on Windows 10.

Preview in Chrome printing dialog: 
![image](https://user-images.githubusercontent.com/6417047/40307713-522c99a8-5d0c-11e8-92d7-fcb3e02b7018.png)

Content of the printing page (if you close the printing dialog): 
![image](https://user-images.githubusercontent.com/6417047/40307731-628f1794-5d0c-11e8-884a-76bf8d83967a.png)

Resulting PDF: 
![image](https://user-images.githubusercontent.com/6417047/40307737-68d2689a-5d0c-11e8-9427-6f52751ca66f.png)

**Comment by calculuschild** [comment] 2018-05-21 12:49
I cannot reproduce this on three different machines (and a phone), so debugging this might be tricky. I imagine this is some recent issue with Chrome if it started popping up on GMBinder as well, and hopefully it will resolve itself on its own.

In the mean time, if this doesn't happen on any of the other snippets (Note, Monster Stat Block, etc.), then I see one possible thing in common between these two.

Could someone try adding this bit to their document and see if it fixes the problem?

```
<style>
    .phb .classTable {
        border-image-repeat: stretch;
    }
    .phb .descriptive {
        border-image-repeat: stretch;
    }
</style>
```

**Comment by Fulminero** [comment] 2018-05-21 13:09
I've created an account just to tell you that your solution worked perfectly for me, as i had the same problem for a couple of weeks. Great job!

**Comment by Rogkun** [comment] 2018-05-21 15:04
@calculuschild 

Also tested, and it works. Thank you so much. You have no idea how much this means to me.

**Comment by Hageshii01** [comment] 2018-05-22 15:21
@calculuschild  Created an account to come and report the issue which I just experienced today, saw the work-around, implemented it, and it worked for me as well (as long as the bit is there; deleting it (and making sure that the brew is saved) and trying to make a pdf reverts it back to the broken format).

**Comment by sensorythought** [comment] 2018-05-28 05:04
I've had the same problem. The fix by calculuschild seems to work.
I spent AGES trying to work this one out.

**Comment by PSDNDFUN** [comment] 2018-06-17 00:38
Took me a while of fidgeting with it but I got it to work eventually will try it on other documents as well thanks.

**Comment by talktocory** [comment] 2018-06-19 23:50
Thank you so much @calculuschild !  I made a 129 page DMs guide for myself and just about to put my fist through the computer screen when I went to start printing it out.

**Comment by Joebing69** [comment] 2018-08-16 00:35
I was about to lose my shit when this happened to an adventure I'm running as a pre-release. Thankfully I stumbled across this thread. Thanks @calculuschild 

Will the future fix repair previous files saved or should we just patch them to be safe?

**Comment by calculuschild** [comment] 2018-08-17 14:25
The future fix should work for all projects on the site. Unfortunately we are all stuck waiting to hear back from @stolksdorf before we can apply the changes. He has the keys to the kingdom to actually get the fixes live, but we haven't had much luck in contacting him for a while.

**Comment by aelgaras** [comment] 2018-09-07 13:56
Hello everyone. I have this same issue, and I tried using the patch you suggest, but it doesn't fix it for me, it just fixes the descriptive box one. Class tables are still a mess. Any suggestion on how I could fix it? What's the exact place where I should place the patch at? Thanks in advance

**Comment by calculuschild** [comment] 2018-09-07 14:04
It will probably work best at the very beginning of your document. Depending which styles you have in your document you might already have some `<style>` tags. You can just grab the inner part of the above snippet and paste it inside.

Make sure you have the whole piece of code. Note that there is a part that says "classTable" and another part that says "descriptive". You need the "classTable" part if you want it to fix those.

**Comment by aelgaras** [comment] 2018-09-10 10:12
That's what I did, @calculuschild , but for some reason I can't understand, it fixes the descriptive notes, but not the class tables

**Comment by calculuschild** [comment] 2018-11-07 21:28
To anyone who had this problem, we've finally managed to push some changes live. Can someone verify that this has been fixed on the live site? (I was never able to see the issue on my own computer, so any feedback from you all would be great!)

**Comment by calculuschild** [comment] 2018-11-13 13:32
Closing because the fix has finally been pushed live. Thanks for bearing with us on this!

**Closed by calculuschild** 2018-11-13 13:32 UTC
Labels: ready to add
