### ISSUE TITLE
Previous Saves

### ISSUE THREAD

**Issue by HawaiianCoconut** [stolksdorf/homebrewery#545] opened 2017-11-06 05:36 UTC
Is there any way I can return to previous saves because I accidentally deleted everything and when I tried to reset I lost the past 5 hours of work I just did. Please if anyone can help me as soon as possible it would be much appreciated

**Comment by Rhaenon** [comment] 2017-11-06 18:13
If you close the tab and reopen it using ctrl+shift+T it loads up an older version, perhaps you can try that?

**Comment by calculuschild** [comment] 2018-04-26 18:16
Duplicate of #654

**Closed by calculuschild** 2018-04-26 18:16 UTC
Labels: duplicate
