### ISSUE TITLE
Real time version window does not appear.

### ISSUE THREAD

**Issue by HiAverageJoe** [stolksdorf/homebrewery#320] opened 2017-02-01 00:52 UTC
Hey there. I know this is a recent issue thats been going on and I've seen it in closed windows but I figured I would inform you that it is continuing.

While I have only been using Homebrewery for a few days and after just finishing a lot of work I noticed the Real Time version no longer appeared once I closed out of the window or migrated it to a new brewery. I know someone attempted to fix it previously but I don't think it worked.

There is currently no error message and I have already checked every div to no avail. If you can find an issue and a solution I'd appreciate it. 

Keep up the good work! 

[The Issue Brewery](http://homebrewery.naturalcrit.com/edit/BklgEKj0vg)

![bug](https://cloud.githubusercontent.com/assets/25470024/22491043/ca9f8218-e7ee-11e6-866a-af2fd3aa5e01.png)

**Comment by stolksdorf** [comment] 2017-02-01 03:24
Thanks for the example, it will help. I'll try and diagnose the error, but I don't have a lot of faith.

**Comment by calculuschild** [comment] 2017-02-02 05:00
Happens when your <pre>```<div class='wide'>```</pre> tag starts on the same line as other text. Move it to its own line and it renders for me. Doesn't happen with the other divs though, just the wide class.

**Comment by rgiannico** [comment] 2017-02-03 16:39
I had the same problem, it's not a bug, it happens when you are closing tabs in the wrong order. 
If you open an `<h4>` and then a `<div>` you have to close the `</div>` first and the `</h4>` after that. 

This error is also shown on the left of your code, you'll notice your `</h4>` and `</div>` tags are red instead of green. When it happens it means they are in the wrong position. 

Try this:
`<h4> Blah blah blah <div class='wide'> </div></h4>
`

**Comment by stolksdorf** [comment] 2017-02-03 16:52
Interesting. I wonder if that's what's causing the issue in all cases?

 Thankfully in v3 there is no way to mess up tag closures 🎉

**Comment by calculuschild** [comment] 2018-04-10 17:13
Duplicate of #657

**Closed by calculuschild** 2018-04-10 17:13 UTC
