### ISSUE TITLE
Class Table Is Corrupted in Print Preview

### ISSUE THREAD

**Issue by bill-cook** [stolksdorf/homebrewery#744] opened 2018-08-27 20:09 UTC
I wrote this character class: http://homebrewery.naturalcrit.com/share/Hy73_ATZwQ

I used v2.7.4 with Chrome on a Mac. I clicked Get PDF. In the Print Dialog, the class table is corrupted.

Thanks for looking at this. Nice builder, BTW.

- Bill

**Comment by ThreadingFate** [comment] 2018-08-29 11:46
I am having the same exact issue, I think. I'm wondering if your class table also looks like my attachment.
![broken class table](https://user-images.githubusercontent.com/42805164/44785633-8d8ef800-ab5f-11e8-8d81-7ccb7039ec86.png)

**Comment by AlexeySachkov** [comment] 2018-08-29 11:49
Hi,

Please take a look at [this comment](https://github.com/stolksdorf/homebrewery/issues/683#issuecomment-390644400) in #683

**Comment by calculuschild** [comment] 2018-08-29 11:50
Looks like a duplicate of #683.

Please take a look at [this comment](https://github.com/stolksdorf/homebrewery/issues/683#issuecomment-390644400).

**Closed by calculuschild** 2018-08-29 11:50 UTC
