### ISSUE TITLE
Format Issues with Bolding/Italicizing

### ISSUE THREAD

**Issue by AKHugmuffin** [stolksdorf/homebrewery#668] opened 2018-04-20 07:25 UTC
I'm having issues with bolding and italicizing certain text in my brew. (To my knowledge) I am using the correct formatting as it shows up correctly in the preview window, but after saving and returning to my work later, without having changed any coding various words or text blocks are now bold that weren't before, or have been italicized.

http://homebrewery.naturalcrit.com/edit/SkfBqBGD2G

Specific instances from my brew:

Line 22 - Originally was not italicized, and now is. Deleting the line and retyping retains the italics.
Lines 23-30 - Originally was not italicized, and now is. Certain words were bolded, but now the entire block of text is bolded.
Lines 86-89 - Likewise italicized and bolded, when originally only certain words were bolded.
Lines 98-101 - Also italicized and bolded.
Lines 108-109 - Italicized and bolded.
Lines 116-117 - Now italicized and bolded.
Line 118 - No longer creates a break between text blocks.
Line 120 - No longer creates a break between text blocks.
Line 121 - now italicized and bolded.

Not sure if there's an issue I'm not seeing. When I create a printable PDF, the formatting changes are still visible. If someone has suggestions, I would be very appreciative

Best wishes,
AKHugmuffin

**Comment by AKHugmuffin** [comment] 2018-04-21 22:26
Thank you very much! I'll start adding blank lines and see if that makes the difference. I apologize for adding my work to your profile, hopefully you like hastily thrown together builds 😆 

Best wishes,
AKHugmuffin

**Comment by calculuschild** [comment] 2018-04-21 23:43
Great. I am going to close this for now assuming that fixed your problem. Feel free to reopen if you need additional info.

Duplicate of #657 .

**Closed by calculuschild** 2018-04-21 23:43 UTC
Labels: duplicate
