### ISSUE TITLE
Homebrew fails to load

### ISSUE THREAD

**Issue by concolitanos** [stolksdorf/homebrewery#364] opened 2017-03-19 21:11 UTC
A homebrew that was fine yesterday (March 18,2017) doesn't display today. I'm seeing the blue background, the top menu (with v0.0.0), and the edit menu. Both windows (display and code) are empty. I also cannot open the Edit Brew Metadata window. When I go to the Shared page and select Source, the code is there but also not displayed.

### Additional Details

**Share Link** :
http://homebrewery.naturalcrit.com/share/Sy7c7kjU
or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment] 2018-04-11 17:29
Duplicate of #655

**Closed by calculuschild** 2018-04-11 17:29 UTC
Labels: duplicate
