### ISSUE TITLE
Class Tables

### ISSUE THREAD

**Issue by DakotaNichols** [stolksdorf/homebrewery#712] opened 2018-06-22 15:15 UTC
Homebrew content is 127 pages, it does say that it cannot be rendered fully, which I understand.

Issue is that the class tables have their border design all wild and crazy. I have a picture attached to show what it looks like. In my previous versions, the tables came out correctly, and have made no changes to any of the class tables.

Here is the following code that is used.

Now the issue only occurs when converting out to a PDF from the website. Any way this can be looked at?

`<div class='classTable wide'>
##### Artificer
| Level | Proficiency Bonus | Features | Spells Known | 1st level | 2nd level | 3rd level | 4th level | 5th level |
|:---:|:---:|:---|:---:|:---:|:---:|:---:|:---:|:---:|
| 1st | +2 | Artificer Advancement, Tool Expertise | 0 | 0 | 0 | 0 | 0 | 0 |
| 2nd | +2 | Magic Item Analysis, Spellcasting | 2 | 2 | 0 | 0 | 0 | 0 |
| 3rd | +2 | Artificer Advancement | 3 | 3 | 0 | 0 | 0 | 0 |
| 4th | +2 | Ability Score Improvement | 3 | 3 | 0 | 0 | 0 | 0 |
| 5th | +3 | Infuse Magic, Wondrous Invention | 4 | 4 | 2 | 0 | 0 | 0 |
| 6th | +3 | ─ | 4 | 4 | 2 | 0 | 0 | 0 |
| 7th | +3 | Artificer Advancement, Infuse Magic | 5 | 4 | 3 | 0 | 0 | 0 |
| 8th | +3 | Ability Score Improvement | 5 | 4 | 3 | 0 | 0 | 0 |
| 9th | +4 | Wondrous Invention | 6 | 4 | 3 | 2 | 0 | 0 |
| 10th | +4 | ─ | 6 | 4 | 3 | 2 | 0 | 0 |
| 11th | +4 | Artificer Advancement, Superior Attunement | 7 | 4 | 3 | 3 | 0 | 0 |
| 12th | +4 | Ability Score Improvement | 7 | 4 | 3 | 3 | 0 | 0 |
| 13th | +4 | Wondrous Invention | 8 | 4 | 3 | 3 | 1 | 0 |
| 14th | +4 | ─ | 8 | 4 | 3 | 3 | 1 | 0 |
| 15th | +4 | Artificer Advancement | 9 | 4 | 3 | 3 | 2 | 0 |
| 16th | +4 | Ability Score Improvement | 9 | 4 | 3 | 3 | 2 | 0 |
| 17th | +4 | Wondrous Invention | 10 | 4 | 3 | 3 | 3 | 1 |
| 18th | +4 | ─ | 10 | 4 | 3 | 3 | 3 | 1 |
| 19th | +4 | Ability Score Improvement | 11 | 4 | 3 | 3 | 3 | 2 |
| 20th | +4 | Mind of the Artificer, Wondrous Invention | 11 | 4 | 3 | 3 | 3 | 2 |
</div>`

The link is [http://homebrewery.naturalcrit.com/share/HJJi6oaF-](url)

![capture](https://user-images.githubusercontent.com/40496929/41784256-25daaaec-760d-11e8-9b78-8f5205dc08a5.PNG)

**Comment by AlexeySachkov** [comment] 2018-06-23 21:09
Looks like duplicate of #683 

Please take a look at [this comment](https://github.com/stolksdorf/homebrewery/issues/683#issuecomment-390644400).

**Closed** 2018-08-29 11:50 UTC
