### ISSUE TITLE
My Homebrewery project is gone, and Homebrewery shows verson.0.0.0

### ISSUE THREAD

**Issue by Minidude2009** [stolksdorf/homebrewery#587] opened 2017-12-26 15:19 UTC
The title says it all, i've been working on a Homebrewery Project for the last couple weeks, and today i logged on to it, and the page is blank, and all it shows is this.

My other project loads perfectly fine, is there any way of recovering my work?

### Additional Details

**Share Link** :

https://imgur.com/PIz9jsm

</pre></code></details>

**Comment by Tronikart** [comment] 2017-12-28 00:04
Exact same issue here, my other projects are fine, only one suffering from this is the most recent one.

https://imgur.com/a/BKmtw

**Comment by Moi-Brisingr** [comment] 2017-12-28 09:57
Both of you just click the share link, then click the source link. Copy the source code into a new brew.
@Minidude2009 you have an extra closing style tag in line 19 and are missing a closing style tag in line 34.
@Tronikart your closing style tag in line 10 just contains a slash and is missing the word "style".
Save the new brew and delete the old one.
I didn't verify whether these completely solve your problems but generally messed up style tags cause problems like yours.

**Comment by calculuschild** [comment] 2018-04-10 15:52
Duplicate of #655

**Closed by calculuschild** 2018-04-10 15:52 UTC
Labels: duplicate
