### ISSUE TITLE
Class table brakes when exporting to pdf

### ISSUE THREAD

**Issue by Danishnerd** [stolksdorf/homebrewery#582] opened 2017-12-18 22:02 UTC
As titles says, when i export my brew to pdf, some of the text moves in over the other.

![image](https://user-images.githubusercontent.com/34663628/34130266-7cca38ac-e447-11e7-91a2-98794e837024.png)

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by Sansd20** [comment] 2017-12-19 15:03
This, I believe, is a known issue. I have seen it reported before.

**Comment by calculuschild** [comment] 2017-12-19 15:08
Try looking at the issue [here](
https://github.com/stolksdorf/homebrewery/issues/318). There is a solution
at the bottom.

**Comment by Danishnerd** [comment] 2017-12-19 20:22
Thanks, solved my problem :)

**Comment by calculuschild** [comment] 2018-04-10 13:42
Duplicate of #318

**Closed by calculuschild** 2018-04-10 13:42 UTC
