### ISSUE TITLE
Save Issues

### ISSUE THREAD

**Issue by Oddish-Flumph** [stolksdorf/homebrewery#563] opened 2017-12-02 16:06 UTC
I have a brew, of which I have imputed new content multiple times, but it rarely saves the changes made, reverting to the old version. I don't know why it does this, but i'd like it to be addressed.

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by Sansd20** [comment] 2017-12-02 22:34
By chance, do you have the brew open in  another browser window/tab when this happens?

**Comment by Oddish-Flumph** [comment] 2017-12-03 01:58
I have my profile with all my brews open, but no duplicates

**Comment by calculuschild** [comment] 2018-04-10 15:53
Duplicate of #654

**Closed by calculuschild** 2018-04-10 15:53 UTC
Labels: duplicate
