### ISSUE TITLE
Not closing a style tag and saving makes the page unviewable/uneditable

### ISSUE THREAD

**Issue by Hedgehogs4Me** [stolksdorf/homebrewery#530] opened 2017-10-24 07:33 UTC
If you leave a style tag open in a brew (not including </style>), then save the document, the edit page does not give you the text box or preview, instead leaving the top menus and divider but otherwise giving a blank blue background. The share link gives only the top menu and divider, but the Get PDF and Source links work well.

### Additional Details

**Share link**: http://homebrewery.naturalcrit.com/share/SkhPqD3TZ

Tested on Chrome and Firefox on Linux.

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

This page cannot be edited.

<style>

</pre></code></details>

### Suggested Functionality Change

I suggest that one of the following changes be implemented:

- Have the save button be greyed out and the autosave function be disabled with a visible "Oops!" message (similar to the one given when not connected to the Internet) when there is an unclosed style tag.
- When there is an unclosed style tag, add a closing tag when the document is saved.

**Comment by HeruAsatru** [comment] 2017-11-02 21:39
This issue will be resolved with v3, see https://github.com/stolksdorf/homebrewery/issues/541

**Comment by calculuschild** [comment] 2018-04-21 23:52
Duplicate of #655

**Closed by calculuschild** 2018-04-21 23:52 UTC
Labels: duplicate
