### ISSUE TITLE
I can't log in to my account

### ISSUE THREAD

**Issue by DungeonsAndDeDe** [stolksdorf/homebrewery#579] opened 2017-12-15 07:53 UTC
I was working on a homebrew (as one does) and all the applications on my laptop suddenly froze. I had to force quit them all, and when I reopened Google Chrome I was logged out of Natural Crit and it won't let me log in.
I know I have the right username and password because a few hours ago I signed in on a different computer to show my brother something.

Has anyone else had this problem before? Is there a way to fix it? I'd rather not lose 3 days of work.

**Comment by stolksdorf** [comment] 2017-12-18 05:57
There seemed to be some resource issues with my login server over the last few days, I'm still diagnosing the cause of the issue, but it looks resource related. 

If you have the edit links of your brews, you can still work on them and share them even if you aren't logged in. Accounts simply link brews together, so don't worry your work will not be lost. I keep daily backups of all brews.

I'll close this for now because it seems the issue has passed, but please re-open this if there are any more login issues in the future.

**Closed by stolksdorf** 2017-12-18 05:57 UTC
