### ISSUE TITLE
Lost Brew in Two Keystrokes

### ISSUE THREAD

**Issue by RolandDebreton** [stolksdorf/homebrewery#436] opened 2017-07-04 16:03 UTC
Username RolandDebreton

I had made a brew entitled "Flitting Leaf's Delightful Catologue of the Peoples of the Multiverse: An Expanded List of the Races"  I got up to edit it on the Fourth of July and somehow, with two keystrokes, deleted what was 40-80 pages of content.  Needless to say, I look for any kind of archive, cache, undo button, anything. 

I was unaware that it would be possible to do this, which is why I trusted your homebrewery for real time editing and entry rather than as a simple format tool.  Is there any way to get back an archived version of the text. 

Thanks,  Jeremy

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment] 2017-07-04 16:28
I'm not the site owner, but here are my thoughts:

If it's still open, did you try pressing CTRL-Z? That should work as an
undo button as long as you haven't closed it yet.

Otherwise, what worked for me once was doing a google search of my brew
hoping Google had a cached copy. So I searched something like:
"my brew title" site:homebrewery.naturalcrit

Or you can search the file ID instead of your title. The ID would be that
blob of numbers/letters at the very end of the URL. You might also search
the "shared" version, since it has a different ID number and Google may
have cached one but not the other.

**Comment by calculuschild** [comment] 2018-04-11 19:41
Duplicate of #654

**Closed by calculuschild** 2018-04-11 19:41 UTC
