### ISSUE TITLE
So.. my doc looked great this morning, but after clearing my cache it's.. not.

### ISSUE THREAD

**Issue by Ertsatz** [stolksdorf/homebrewery#628] opened 2018-03-03 16:10 UTC
I'm sorry for being vague, but I really don't know how to put exactly what happened. The preview to the right isn't even showing up.  When I checked it out as a PDF, most of everything is where I put it, but there's just a random page where there was a column break before.  I've provided a link below, but I've never worked with anything like Homebrewery before so I really couldn't tell you where I messed up here. 

### Additional Details

[Link Here](https://homebrewery.naturalcrit.com/edit/B1MdQIHdOf)

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by DoctorDan1986** [comment] 2018-03-03 21:56
*shrugs* . Copy your code, start a new brew, and paste the old code in.

**Comment by Moi-Brisingr** [comment] 2018-03-04 01:10
When you put a descriptive text box into a note, every line of the text box has to start with > 
It is fixed in that document now but you should not post edit links to your brews. Everyone can make changes and mess with your brew using the edit link. 
Also there is now a page number reset on the second page so you can use the automatic numbering for your pages now.

**Comment by calculuschild** [comment] 2018-04-10 15:15
Duplicate of #655 .

**Comment by calculuschild** [comment] 2018-04-10 15:16
Duplicate of #655

**Closed by calculuschild** 2018-04-10 15:15 UTC
