### ISSUE TITLE
Can't figure out what I'm doing wrong.

### ISSUE THREAD

**Issue by undeadjebus** [stolksdorf/homebrewery#475] opened 2017-08-27 20:07 UTC
When I select Share, everything looks normal like where I have the preview, but when I select get PDF the Nature Domain looks fine, but under the Tempest Domain, Cleric Level and Spells keep duplicating themselves down my table overlapping with everything else. It is also making a random column break where I put Auril, Eadro underneath the title line.

### Additional Details

![issue](https://user-images.githubusercontent.com/31358704/29753549-5da9492a-8b39-11e7-8a44-dc7217ebe2e3.jpg)

![issue 2](https://user-images.githubusercontent.com/31358704/29753566-a0b5388c-8b39-11e7-995a-c5be6ab037f9.jpg)

or

___
___
> ## Nature Domain
>*Auril, Eadro*
> ___
##### Domain Spells
>| Cleric Level | Spells |
>|:----:|:-------------|
>| 1st  | *animal friendship, speak with animals* |
>| 3rd  | *barkskin, spike growth* |
>| 5th | *plant growth, wind wall* |
>| 7th | *dominate beast, grasping vine* |
>| 9th | *insect plague, tree stride* |
>___
>#### Acolyte of Nature
>At 1st level, you learn one druid cantrip of your choice. You also gain proficiency in one of the following skills of your choice: Animal Handling, Nature, or Survival.
>#### Bonus Proficiency
>Also at 1st level, you gain proficiency with heavy armor.
>#### Channel Divinity: Charm Animals and Plants
>Starting at 2nd level, you can use your Channel Divinity to charm animals and plants</br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;As an action, you present your holy symbol and invoke the name of your deity. Each beast or plant
>
>creature that can see you within 30 feet of you must make a Wisdom saving throw. If the creature fails its saving throw, it is charmed by you for 1 minute or until it takes damage. While it is charmed by you, it is friendly to you and other creatures you designate.
>#### Dampen Elements
>Starting at 6th level, when you or a creature within 30 feet of you takes acid, cold, fire, lightning, or thunder damage, you can use your reaction to grant resistance to the creature against that instance of damage.
>#### Divine Strike
>At 8th level, you gain the ability to infuse your weapon strikes with divine energy. Once on each of your turns when you hit a creature with a weapon attack, you can cause the attack to deal an extra 1d8 cold, fire, or lightning damage (your choice) to the target. When you reach 14th level, the extra damage increases to 2d8.
>#### Master of Nature
>At 17th level, you gain the ability to command animals and plant creatures. While creatures are charmed by your Charm Animals and Plants feature, you can take a bonus action on your turn to verbally command what each of those creatures will do on its next turn.

___
___
> ## Tempest Domain
>*Auril, Eadro*
>___
 ##### Domain Spells
| Cleric Level | Spells |
|:----:|:-------------|
| 1st  | *charm person, disguise self* |
| 3rd  | *mirror image, pass without trace* |
| 5th | *blink, dispel magic* |
| 7th | *dimension door, polymorph* |
| 9th | *dominate person, modify memory* |
___
>#### Bonus Proficiences
>At 1st level, you gain proficiencey with martial weapons and heavy armor.
>#### Wrath of the Storm
>Also at 1st level, you can thunderously rebuke attackers. When a creature within 5 feet of you can see hits you with an attack, you can use your reaction to cause the creature to make a Dexterity saving throw. The creature takes 2d8 lightning or thunder damage (your choice) on a failed saving throw, and half as much damage on a successful one.</br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;You can use this feature a number of times equal to your Wisdom modifier (a minimum of once). You regain all expended uses when you finish a long rest.
>#### Channel Divinity: Destructive Wrath
>Starting at 2nd level, you can use your Channel Divinity to wield the power of the storm with unchecked ferocity.
>When you roll lightning or thunder damage, you can use your Channel Divinity to deal maximum damage, instead of rolling.
>#### Thunderbolt Strike
>At 6th level, when you deal lightning damage to a Large or smaller creature, you can also push it up to 10 feet away from you.
>#### Divine Strike
>at 8th level, you gain the ability to infuse your weapon strikes with divine energy. Once on each of your turns when you hit a creature with a weapon attack, you can cause the attack to deal an extra 1d8 thunder damage to the target. When you reach 14th level , the extra damage increases to 2d8.
>#### Stormborn
>At 17th level, you have a flying speed equal to your current walking speed whenever you are not underground or indoors.

**Comment by calculuschild** [comment] 2018-04-11 17:30
Duplicate of #318

**Closed by calculuschild** 2018-04-11 17:30 UTC
