### ISSUE TITLE
Saved Projects not showing up

### ISSUE THREAD

**Issue by Reliva** [stolksdorf/homebrewery#536] opened 2017-10-29 20:27 UTC
Whenever I create a project and save it, share it to who i want and close my browser. When I return in the future and click recent brews or my name nothing happens...it dosen't take me to my saved brews page and anything i had i lose.

**Comment by calculuschild** [comment] 2018-04-21 23:57
Duplicate of #577

**Closed by calculuschild** 2018-04-21 23:57 UTC
Labels: duplicate
